/* ---------- Lean Grammar Handbook Data ---------- */
(function(root){
  const sources = Object.freeze({
    'merkle-beginning-2020': Object.freeze({
      kind:'organization',
      authors:'Benjamin L. Merkle and Robert L. Plummer',
      title:'Beginning with New Testament Greek: An Introductory Study of the Grammar and Syntax of the New Testament',
      edition:'First edition',
      publication:'Nashville: B&H Academic, 2020',
      note:'Used for introductory sequence, familiar terminology, and the progression from forms to reading.'
    }),
    'merkle-going-2016': Object.freeze({
      kind:'organization-and-content',
      authors:'Andreas J. Köstenberger, Benjamin L. Merkle, and Robert L. Plummer',
      title:'Going Deeper with New Testament Greek: An Intermediate Study of the Grammar and Syntax of the New Testament',
      edition:'First edition',
      publication:'Nashville: B&H Academic, 2016',
      note:'Used selectively for intermediate syntax categories and their reading value; the Handbook does not reproduce its taxonomies.'
    }),
    'merkle-gems-2019': Object.freeze({
      kind:'organization',
      authors:'Benjamin L. Merkle',
      title:'Exegetical Gems from Biblical Greek: A Refreshing Guide to Grammar and Interpretation',
      edition:'First edition',
      publication:'Grand Rapids: Baker Academic, 2019',
      note:'Used for the forms-to-interpretation emphasis and chapter-level topic grouping, not as a source of copied prose.'
    }),
    'machen-1923': Object.freeze({
      kind:'content-and-forms',
      authors:'J. Gresham Machen',
      title:'New Testament Greek for Beginners',
      edition:'1923 first edition',
      publication:'New York: The Macmillan Company, 1923',
      scan:'CCEL digital facsimile v0.1; printed page images checked for cited forms',
      note:'Foundational Greek morphology and concise grammatical explanations.'
    }),
    'pratico-van-pelt-2019': Object.freeze({
      kind:'organization-and-terminology',
      authors:'Gary D. Pratico and Miles V. Van Pelt',
      title:'Basics of Biblical Hebrew Grammar',
      edition:'Third edition',
      publication:'Grand Rapids: Zondervan Academic, 2019',
      note:'Used for visible terminology, strong-before-weak sequencing, and grouping of nouns, suffixes, stems, and weak verbs.'
    }),
    'gesenius-1910': Object.freeze({
      kind:'content-and-forms',
      authors:'Wilhelm Gesenius; edited by E. Kautzsch; translated and revised by A. E. Cowley',
      title:"Gesenius' Hebrew Grammar",
      edition:'Second English edition, revised from the 1909 twenty-eighth German edition',
      publication:'Oxford: Clarendon Press, 1910',
      scan:'Internet Archive/Wikisource page-image reproduction, item geseniushebrewgr00geseuoft',
      note:'Foundational Hebrew descriptions and the row-level source for existing Hebrew forms.'
    }),
    'puritan-parser-editorial': Object.freeze({
      kind:'app-authored',
      authors:'The Puritan Parser editorial synthesis',
      title:'Reading workflows and recognition guidance',
      edition:'v1.3.7',
      publication:'Local application content, 2026',
      note:'Concise reading procedures and ambiguity checks synthesized for this app; not quotations from a single grammar.'
    })
  });

  const organization = (sourceId, locations, scope) => ({ sourceId, locations, scope, support:'organization' });
  const content = (sourceId, locations, scope, support='partial') => ({ sourceId, locations, scope, support });
  const appGuidance = scope => ({ sourceId:'puritan-parser-editorial', locations:['v1.3.7 Grammar Handbook editorial pass'], scope, support:'synthesis' });
  const article = data => Object.freeze({
    aliases:[], searchTerms:[], overview:[], recognitionCues:[], commonFunctions:[], commonPitfalls:[], examples:[], relatedChartIds:[], relatedArticleIds:[], advancedNote:'',
    ...data,
    sources:Object.freeze(data.sources)
  });

  const sections = Object.freeze([
    { id:'greek-nouns-agreement', language:'greek', title:'Nouns, the Article, and Agreement', summary:'Read nominal forms through case, agreement, and context.', order:10 },
    { id:'greek-indicative-system', language:'greek', title:'The Indicative Verb System', summary:'Recognize tense stems, endings, and principal-part relationships.', order:20 },
    { id:'greek-voice-mood', language:'greek', title:'Voice and Mood', summary:'Separate visible verb morphology from contextual function.', order:30 },
    { id:'greek-nonfinite', language:'greek', title:'Infinitives and Participles', summary:'Read verbal nouns and verbal adjectives without forcing one translation.', order:40 },
    { id:'greek-markers', language:'greek', title:'Pronouns, Prepositions, and Clause Markers', summary:'Use small words to trace relationships and clause boundaries.', order:50 },
    { id:'greek-reading', language:'greek', title:'Reading Greek Sentences', summary:'Build a provisional reading from the Greek before checking English.', order:60 },
    { id:'hebrew-nouns-construct', language:'hebrew', title:'Nouns, Adjectives, and Construct Forms', summary:'Read gender, number, state, and agreement together.', order:10 },
    { id:'hebrew-suffixes-prepositions', language:'hebrew', title:'Pronouns, Suffixes, and Prepositions', summary:'Separate attached elements before deciding the whole word.', order:20 },
    { id:'hebrew-qal-conjugations', language:'hebrew', title:'The Qal Stem and Hebrew Conjugations', summary:'Use the Qal strong verb as the recognition baseline.', order:30 },
    { id:'hebrew-derived-stems', language:'hebrew', title:'Derived Stems', summary:'Recognize stem patterns without forcing a fixed gloss.', order:40 },
    { id:'hebrew-weak-verbs', language:'hebrew', title:'Weak Verbs', summary:'Compare a visible weak form with the expected strong pattern.', order:50 },
    { id:'hebrew-reading', language:'hebrew', title:'Reading Hebrew Clauses', summary:'Identify clause structure, attachments, and verbal sequence before translation.', order:60 }
  ].map(Object.freeze));

  const articles = Object.freeze([
    article({ id:'greek-cases-agreement', language:'greek', sectionId:'greek-nouns-agreement', order:10, title:'Cases and Agreement', summary:'Case forms mark relationships, but the surrounding construction determines the precise function.',
      aliases:['case system','case uses','noun endings','nominative genitive dative accusative vocative','morphology terminology','Morphology Guide','Parsing Abbreviations','N-NSM'], searchTerms:['declension','subject','direct object','possession','indirect object','address','agreement','ambiguous forms'],
      overview:['Greek nouns, articles, adjectives, and many pronouns show case, number, and gender. The five cases are best learned as a system rather than as five isolated translation rules. Nominative commonly marks a subject or predicate nominative; genitive commonly marks a close relationship; dative commonly marks an indirect, locative, or instrumental relationship; accusative commonly marks a direct object or extent; vocative addresses someone directly. These are starting points, not automatic glosses.','An ending narrows the possibilities, while agreement and sentence structure usually settle the reading. First- and second-declension endings are often transparent; third-declension stems may change before their endings. Begin with the article when one is present, then compare every agreeing word.'],
      recognitionCues:['Locate the article and compare its case, number, and gender with nearby nominals.','Use a governing preposition or verb before choosing a case function.','Treat identical neuter nominative and accusative forms as context-dependent.'],
      commonFunctions:['Nominative: subject or predicate relationship.','Genitive: belonging, source, description, or another close relation.','Dative: recipient, sphere, location, means, or association.','Accusative: direct object, extent, destination, or adverbial limitation.','Vocative: direct address.'],
      commonPitfalls:['Do not translate every genitive with the same English construction.','Do not decide subject and object from word order alone.','Do not treat a parsed case label as a complete syntactic explanation.'],
      examples:[{ text:'ὁ λόγος', reference:'John 1:1', translation:'the Word', language:'greek' },{ text:'τοῦ θεοῦ', reference:'John 1:1', translation:'of God', language:'greek' }],
      relatedChartIds:['greek-first-declension-feminine-hora-graphe','greek-second-declension-masculine-logos','greek-third-declension-dental-elpis'], relatedArticleIds:['greek-article-adjectives','greek-reading-workflow'],
      sources:[organization('merkle-beginning-2020',['chs. 2–3, 14, 16'], 'Introductory sequence for declensions and agreement'), organization('merkle-gems-2019',['chs. 3–7, 11'], 'Case-and-adjective grouping with reading value'), content('machen-1923',['pp. 17–26; §§26–43','pp. 225–231; §§555–573'], 'Foundational case, declension, and agreement descriptions'), appGuidance('Recognition order and ambiguity checklist')]
    }),
    article({ id:'greek-article-adjectives', language:'greek', sectionId:'greek-nouns-agreement', order:20, title:'The Article and Adjectives', summary:'The article is a strong agreement signal and helps distinguish attributive, predicate, and substantival relationships.',
      aliases:['article endings','adjective endings','attributive position','predicate position','substantival adjective'], searchTerms:['article noun relationship','agreement','predicate nominative','anarthrous','autos'],
      overview:['The Greek article agrees with its head in case, number, and gender. Because its forms are distinctive, it often identifies the grammatical shape of a phrase before the noun ending does. An article may mark a noun phrase as identifiable in context, but it should not be reduced to a mechanical rule that every article equals “the” or every article-less noun is indefinite.','Adjectives likewise agree with the noun they modify. In a common attributive pattern, the article encloses or repeats around the adjective and noun; in a common predicate pattern, the adjective stands outside the article-noun group. An adjective can also stand substantivally, with an implied noun supplied from context.'],
      recognitionCues:['Group words that share case, number, and gender.','Compare article placement before labeling an adjective attributive or predicate.','When no noun appears, ask whether an adjective or participle is functioning substantivally.'],
      commonFunctions:['Identify a noun phrase already known in the discourse.','Link an adjective directly to a noun or present it as a predicate.','Turn an adjective or participle into a substantive expression.'],
      commonPitfalls:['Article use is not identical to English definiteness.','Agreement does not require adjacent word order.','A predicate adjective need not follow its noun.'],
      examples:[{ text:'ὁ ποιμὴν ὁ καλός', reference:'John 10:11', translation:'the good shepherd', language:'greek' }],
      relatedChartIds:['greek-adjective-first-second-agathos','greek-adjective-third-declension-alethes'], relatedArticleIds:['greek-cases-agreement','greek-pronouns-prepositions'],
      sources:[organization('merkle-beginning-2020',['chs. 2–3, 16'], 'Article and adjective sequence'), organization('merkle-going-2016',['chs. 8, 11'], 'Article and adjective syntax categories'), content('machen-1923',['pp. 24–26; §§39–43','pp. 150, 230–231; §§325, 568–573'], 'Article and adjective agreement'), appGuidance('Phrase-grouping procedure')]
    }),
    article({ id:'greek-indicative-system', language:'greek', sectionId:'greek-indicative-system', order:10, title:'Reading the Indicative System', summary:'Read an indicative through person, number, tense stem, voice, and its place in the clause.',
      aliases:['indicative verbs','tense form','verbal aspect','primary endings','secondary endings','augment','reduplication','V-AAI-3S'], searchTerms:['present imperfect future aorist perfect pluperfect','person number','tense stem','aspect'],
      overview:['A finite indicative normally carries person and number and presents an assertion in its clause. Its tense-form combines a stem with voice markers, connecting vowels, and personal endings. Present and future systems normally use primary endings; imperfect, aorist, and pluperfect indicatives normally use secondary endings. Past indicatives commonly show an augment, while perfect-system forms commonly show reduplication.','For reading, begin with the visible stem rather than an English tense label. Present and imperfect forms commonly present an action from within or as ongoing; aorist forms commonly present it as a whole; perfect forms commonly present a completed action with a resulting state. Time is clearest in the indicative, but discourse and lexical meaning still matter. These cues are intentionally cautious because verbal-aspect terminology is debated.'],
      recognitionCues:['Find the personal ending and identify person and number.','Check for augment, reduplication, σ, θη, or a changed second-aorist stem.','Separate the tense stem from the ending before consulting a chart.'],
      commonFunctions:['Present: commonly current, repeated, customary, or generally true action.','Imperfect: commonly past action viewed as ongoing or repeated.','Future: commonly anticipated action.','Aorist: commonly a past event presented as a whole.','Perfect: commonly a present state resulting from a completed action.'],
      commonPitfalls:['Do not force every present into “is doing” or every aorist into one English tense.','An augment is tied to past indicative formation, not to every aorist form.','Morphological tense-form does not settle every contextual nuance.'],
      examples:[{ text:'ἐλύθησαν', reference:'Representative', translation:'they were released', language:'greek' }],
      relatedChartIds:['greek-present-active-indicative-lyo','greek-imperfect-active-indicative-lyo','greek-first-aorist-active-indicative-lyo','greek-perfect-active-indicative-lyo'], relatedArticleIds:['greek-principal-parts','greek-voice','greek-moods'],
      sources:[organization('merkle-beginning-2020',['chs. 4–6, 10–15'], 'Forms-first indicative progression'), organization('merkle-going-2016',['chs. 12–17'], 'Cautious aspect and indicative-system grouping'), content('machen-1923',['pp. 20, 58–93; §§18, 110–202','pp. 183–187; §§426–450'], 'Indicative formation, endings, augment, and perfect system'), appGuidance('Stem-first reading sequence and cautions')]
    }),
    article({ id:'greek-principal-parts', language:'greek', sectionId:'greek-indicative-system', order:20, title:'Principal Parts and Tense Stems', summary:'Principal parts connect a lexical form to stems that may look very different in the text.',
      aliases:['principal part','lexical form','contract verb','liquid verb','mi verb','μί verb','athematic verb'], searchTerms:['tense stems','second aorist','future passive','perfect middle passive','irregular verb'],
      overview:['A Greek dictionary normally lists a verb under its present active first-person singular, but other systems may be built from a different stem. The six principal parts provide the anchors for present/imperfect, future active and middle, aorist active and middle, perfect active, perfect middle/passive, and aorist/future passive systems. A reader who recognizes the relevant principal part can connect an unfamiliar surface form back to its lexical entry.','Sound changes make this especially important for liquid verbs, contract verbs, and many common irregular verbs. Contract verbs hide a stem-final vowel in the present system. μι-verbs attach endings more directly to an athematic stem and may show reduplication or vowel alternation. When a form looks unrelated to the lexical form, identify its formative and ending, then consult the principal-part or specialized chart.'],
      recognitionCues:['Remove augment and personal ending before comparing stems.','Look for σ, κ, reduplication, or θη as system clues.','Test whether contraction or a second-aorist stem explains the apparent mismatch.'],
      commonFunctions:['Connect a parsed form to its lexical entry.','Predict which tense systems share a stem.','Distinguish active/middle aorists from aorist-passive formation.'],
      commonPitfalls:['Principal parts are lexical facts, not a generator for unattested forms.','Do not assume every verb has a regular first aorist in σ.','Do not expand an irregular chart by analogy.'],
      examples:[{ text:'λείπω · ἔλιπον', reference:'Machen §593', translation:'present lexical form · second aorist', language:'greek' }],
      relatedChartIds:['greek-principal-parts-lyo','greek-principal-parts-leipo-second-aorist','greek-alpha-contract-present-active-timao','greek-didomi-present-active-indicative'], relatedArticleIds:['greek-indicative-system','greek-moods'],
      sources:[organization('merkle-beginning-2020',['chs. 7, 11–13, 24'], 'Contract, aorist, liquid, and μι-verb grouping'), content('machen-1923',['pp. 77, 92–93, 183–187, 238; §§159, 197–202, 426–450, 589','pp. 239–249; §§590–601'], 'Principal-part relationships and representative specialized paradigms'), appGuidance('Surface-form recovery procedure')]
    }),
    article({ id:'greek-voice', language:'greek', sectionId:'greek-voice-mood', order:10, title:'Active, Middle, and Passive Voice', summary:'Voice morphology frames a participant relationship, but lexical meaning and context determine the best reading.',
      aliases:['middle voice','passive voice','deponent','middle passive'], searchTerms:['active voice','deponency','agent','subject affected'],
      overview:['Active morphology commonly presents the subject as carrying out the action. Passive morphology commonly presents the subject as receiving or undergoing it. Middle morphology commonly presents the subject as especially involved in the action, but the exact relationship varies by verb. In the present, imperfect, and perfect systems, middle and passive forms are morphologically identical; context and lexical usage must decide between them.','The traditional label “deponent” can alert a reader that a verb lacks ordinary active forms or regularly appears in middle morphology with an active-looking English gloss. It should not imply that the morphology is meaningless. First identify the actual voice form, then consult the verb’s lexical behavior and the participants in the clause.'],
      recognitionCues:['Identify the tense system before distinguishing voice.','Expect shared middle/passive morphology outside the aorist and future passive systems.','Check whether θη marks an aorist- or future-passive stem.'],
      commonFunctions:['Active commonly profiles the subject as actor.','Middle commonly profiles subject involvement, self-interest, reciprocity, or lexical middle meaning.','Passive commonly profiles the subject as affected by an action.'],
      commonPitfalls:['A middle form is not automatically reflexive.','A passive-looking English translation does not replace morphological analysis.','“Deponent” is a lexical description, not a fourth voice.'],
      relatedChartIds:['greek-present-middle-passive-indicative-lyo','greek-first-aorist-middle-indicative-lyo','greek-aorist-passive-indicative-lyo'], relatedArticleIds:['greek-indicative-system','greek-moods','greek-participles'],
      sources:[organization('merkle-beginning-2020',['chs. 4–5, 10–12'], 'Voice introduced inside the verb systems'), organization('merkle-going-2016',['chs. 13–17'], 'Voice read within tense-form and syntax'), content('machen-1923',['pp. 58–59, 75, 82–93; §§110–112, 154–202'], 'Middle/passive morphology and distinct aorist-passive formation'), appGuidance('Context-and-lexicon decision procedure')]
    }),
    article({ id:'greek-moods', language:'greek', sectionId:'greek-voice-mood', order:20, title:'Indicative, Subjunctive, Imperative, and Optative', summary:'Mood marks how a verbal form presents an action, while particles and clause context refine its function.',
      aliases:['subjunctive','imperative','optative','mood'], searchTerms:['indicative','hortatory','prohibition','wish','purpose clause','condition'],
      overview:['The indicative normally presents an assertion. The subjunctive commonly appears in projected, contingent, purpose, or exhortational settings and often has a long connecting vowel, ω or η. The imperative directly presents a command or appeal and has second- and third-person forms. The optative is comparatively rare in the New Testament and may express a wish or appear in other marked contexts.','Morphological mood and contextual function are not identical. A subjunctive can serve different constructions depending on particles such as ἵνα or ἐάν; a command may also be expressed without an imperative. Identify the form first, then read the clause marker, negation, and discourse setting.'],
      recognitionCues:['Look for long ω/η connecting vowels in regular subjunctives.','Expect no augment outside the indicative.','Check particles such as ἵνα, ἐάν, and μή before naming a function.'],
      commonFunctions:['Indicative: assertion and many questions.','Subjunctive: purpose, projection, contingency, exhortation, or prohibition in appropriate constructions.','Imperative: command, request, or appeal.','Optative: introductory recognition of wishes and other rare marked uses.'],
      commonPitfalls:['Do not label every subjunctive “uncertain.”','Do not infer function from the ending without the clause marker.','The optative is included for recognition, not as an exhaustive syntax system.'],
      relatedChartIds:['greek-present-active-subjunctive-lyo','greek-aorist-active-subjunctive-lyo','greek-present-active-imperative-lyo','greek-didomi-nonindicative'], relatedArticleIds:['greek-indicative-system','greek-clause-markers','greek-reading-workflow'],
      sources:[organization('merkle-beginning-2020',['chs. 22–23'], 'Introductory mood sequence and terminology'), organization('merkle-gems-2019',['chs. 18–20'], 'Selective reading significance of moods'), content('machen-1923',['pp. 128–131; §§269–282','pp. 177–180; §§404–423'], 'Subjunctive and imperative formation and introductory use'), appGuidance('Form-then-particle workflow and optative limitation')]
    }),
    article({ id:'greek-infinitives', language:'greek', sectionId:'greek-nonfinite', order:10, title:'Infinitives', summary:'An infinitive is a verbal noun whose role is determined by its governing construction.',
      aliases:['articular infinitive','infinitival subject','complementary infinitive'], searchTerms:['verbal noun','infinitive subject','to plus verb','tense form voice'],
      overview:['Greek infinitives carry tense-form and voice but do not carry finite person and number endings. They can complete the sense of another verb, function as a subject or complement, or appear with an article and preposition in an articular construction. Their implied subject may be supplied by the governing verb or expressed in the accusative when a distinct subject is needed.','The tense-form of an infinitive normally contributes aspect rather than independent time. Present forms commonly present an action from within; aorist forms commonly present it as a whole; perfect forms commonly emphasize a resulting state. Translate only after identifying the infinitive’s relationship to the finite verb and surrounding particles.'],
      recognitionCues:['Common endings include -ειν, -σαι, -θῆναι, -σθαι, and -έναι.','Look for a preceding article and preposition before treating an infinitive as merely complementary.','Identify any accusative noun or pronoun that may serve as the infinitival subject.'],
      commonFunctions:['Complete verbs of ability, desire, beginning, or obligation.','Serve as a subject or complement.','Form articular constructions that express purpose, time, cause, or another contextual relation.'],
      commonPitfalls:['Do not assign independent time from tense-form alone.','Do not assume every accusative near an infinitive is its subject.','An English “to” phrase may obscure the Greek construction.'],
      examples:[{ text:'λύειν', reference:'Representative', translation:'to release', language:'greek' }],
      relatedChartIds:['greek-present-active-infinitive-lyo','greek-aorist-passive-infinitive-lyo','greek-infinitive-system-index-lyo'], relatedArticleIds:['greek-participles','greek-clause-markers','greek-reading-workflow'],
      sources:[organization('merkle-beginning-2020',['ch. 21'], 'Introductory infinitive grouping'), organization('merkle-gems-2019',['ch. 24'], 'Selective syntax and reading value'), content('machen-1923',['pp. 136–137; §§293–297','pp. 183, 186, 238; §§427, 443, 589'], 'Infinitive forms and foundational syntax'), appGuidance('Governing-construction checklist')]
    }),
    article({ id:'greek-participles', language:'greek', sectionId:'greek-nonfinite', order:20, title:'Participles', summary:'A participle is a verbal adjective: parse its verbal stem and its nominal agreement before choosing a function.',
      aliases:['genitive absolute','adverbial participle','substantival participle','attendant circumstance','adjectival participle'], searchTerms:['verbal adjective','circumstantial','agreement','participle'],
      overview:['Greek participles combine a tense-form and voice with case, number, and gender. Their nominal endings connect them to a noun or allow them to stand substantivally; their verbal stem can take complements and modifiers. Parse both halves before translating. An articular participle often functions adjectivally or substantivally, while an anarthrous participle often relates adverbially to the main verb, though context remains decisive.','Adverbial participles may express time, cause, concession, means, manner, condition, or another circumstance. A genitive absolute normally contains a genitive participle and a genitive subject that is grammatically less integrated with the main clause. “Attendant circumstance” can describe a participle closely coordinated with a finite verb, but it is a cautious reading category rather than an automatic translation rule.'],
      recognitionCues:['Match case, number, and gender with a possible head noun.','Use the article as an early clue to adjectival or substantival use.','Locate the finite verb before deciding how an adverbial participle relates to it.'],
      commonFunctions:['Modify a noun adjectivally.','Stand substantivally for a person or group.','Describe a circumstance related to the main verb.','Form a genitive absolute with its own genitive subject.'],
      commonPitfalls:['Tense-form usually marks aspect and relative relation, not independent time.','Do not force every anarthrous participle into the same adverbial category.','Do not call every genitive participle a genitive absolute.'],
      examples:[{ text:'λέγων', reference:'Matthew 3:2', translation:'saying', language:'greek' },{ text:'γεγραμμένον', reference:'Matthew 4:4', translation:'written', language:'greek' }],
      relatedChartIds:['greek-present-active-participle-lyo','greek-aorist-active-participle-lyo','greek-perfect-middle-passive-participle-lyo','greek-participle-system-index-lyo'], relatedArticleIds:['greek-cases-agreement','greek-infinitives','greek-reading-workflow'],
      sources:[organization('merkle-beginning-2020',['chs. 17–19'], 'Participle formation sequence'), organization('merkle-going-2016',['chs. 21–23'], 'Adverbial, verbal, and periphrastic categories'), organization('merkle-gems-2019',['chs. 21–23'], 'Reading-focused participle grouping'), content('machen-1923',['pp. 102–121; §§226–259','pp. 232–234, 238; §§576–580, 589'], 'Participle formation and declension'), appGuidance('Agreement-first function checklist and cautious attendant-circumstance wording')]
    }),
    article({ id:'greek-pronouns-prepositions', language:'greek', sectionId:'greek-markers', order:10, title:'Pronouns and Prepositions', summary:'Pronouns trace participants; prepositions narrow relationships without supplying a fixed one-word gloss.',
      aliases:['personal pronoun','demonstrative pronoun','relative pronoun','interrogative indefinite','autos','αὐτός','prepositions and particles'], searchTerms:['antecedent','case relationship','ἐν','εἰς','ἐκ','διά'],
      overview:['Personal pronouns identify discourse participants, while demonstratives point, relative pronouns introduce clauses, and interrogative or indefinite pronouns ask or generalize. αὐτός is especially context-sensitive: it may function as a third-person pronoun, intensify a noun or pronoun, or express “same” in an article-bearing construction. Agreement and position help distinguish these uses.','A preposition forms a phrase with a particular case. The case relationship and the lexical range of the preposition work together; neither should be reduced to one English word. Some prepositions occur with more than one case and change their common relationship accordingly. Read the entire phrase, then decide how it connects to the verb or noun it modifies.'],
      recognitionCues:['Find a pronoun’s antecedent from agreement and discourse, not proximity alone.','Distinguish accented τίς (“who?/what?”) from enclitic τις (“someone/something”).','Identify the preposition and governed case as one unit.'],
      commonFunctions:['Track speakers, referents, and relative-clause connections.','Mark location, direction, source, means, agency, or another relation.','Use αὐτός pronominally, intensively, or for identity according to position.'],
      commonPitfalls:['A relative pronoun agrees with its antecedent in gender and number but takes case from its role in its own clause.','Do not assign a preposition one gloss in every context.','Do not assume the nearest noun is a pronoun’s antecedent.'],
      examples:[{ text:'ἐν ἀρχῇ', reference:'John 1:1', translation:'in the beginning', language:'greek' },{ text:'αὐτός', reference:'Matthew 1:21', translation:'he', language:'greek' }],
      relatedChartIds:['greek-pronouns-personal-autos-singular','greek-pronoun-demonstrative-houtos','greek-pronoun-relative-hos','greek-pronouns-interrogative-indefinite-singular'], relatedArticleIds:['greek-article-adjectives','greek-clause-markers','greek-reading-workflow'],
      sources:[organization('merkle-beginning-2020',['chs. 8–9, 20'], 'Preposition and pronoun grouping'), organization('merkle-gems-2019',['chs. 25–26'], 'Reading contribution of pronouns and prepositions'), content('machen-1923',['pp. 170–173, 235; §§384–398, 581–583'], 'Pronoun forms and foundational uses'), appGuidance('Antecedent and prepositional-phrase workflow')]
    }),
    article({ id:'greek-clause-markers', language:'greek', sectionId:'greek-markers', order:20, title:'Clause Markers and Negation', summary:'Conjunctions, particles, and negatives reveal how clauses relate before every word is resolved.',
      aliases:['conjunctions','particles','negation','καί','δέ','γάρ','οὖν','μέν δέ','οὐ μή','subordinate clause markers'], searchTerms:['ἵνα','ὅτι','ἐάν','ὅς','purpose result condition indirect question'],
      overview:['Small words often provide the sentence map. καί may coordinate or add emphasis; δέ commonly marks a new step or mild contrast; γάρ commonly supplies support or explanation; οὖν commonly marks an inference or continuation; μέν … δέ organizes a balanced contrast. Their contribution depends on discourse, so a fixed one-word gloss can obscure the relationship.','Greek normally uses οὐ with indicative statements and μή in many non-indicative, projected, or prohibited contexts, but each also belongs to established constructions. Clause markers such as ὅτι, ἵνα, ἐάν, relative pronouns, and interrogative forms help identify subordinate clauses. Mark the boundary first; then determine whether the clause supplies content, purpose, result, condition, description, or a question.'],
      recognitionCues:['Circle or mark conjunctions before parsing the clause interior.','Pair μέν with a following δέ when the discourse supports it.','Read negation together with mood and clause type.'],
      commonFunctions:['Coordinate words or clauses.','Explain, infer, contrast, or advance an argument.','Introduce content, purpose, condition, result, relative description, or indirect question.'],
      commonPitfalls:['Do not insist that καί always means only “and.”','Do not treat δέ as a strong contrast in every occurrence.','The οὐ/μή distinction is grammatical and constructional, not a simple objective/subjective opposition.'],
      relatedChartIds:[], relatedArticleIds:['greek-moods','greek-pronouns-prepositions','greek-reading-workflow'],
      sources:[organization('merkle-gems-2019',['chs. 28–29'], 'Conjunction, particle, and conditional grouping'), organization('merkle-going-2016',['chs. 28–29'], 'Clause-marker and conditional framework'), content('machen-1923',['pp. 128–131, 177–180; §§269–282, 404–423'], 'Mood and negation foundations for common constructions','partial'), appGuidance('Clause-boundary procedure and restrained glossing')]
    }),
    article({ id:'greek-reading-workflow', language:'greek', sectionId:'greek-reading', order:10, title:'A Workflow for Reading Greek Sentences', summary:'Build the clause from finite verbs, connectors, and agreement before consulting English.',
      aliases:['reading Greek sentences','sentence workflow','clause boundaries','word order'], searchTerms:['finite verb','subject complement','subordinate clause','provisional reading'],
      overview:['Greek word order is flexible because morphology carries many relationships. A useful first pass therefore follows structure rather than English order. Locate the finite verb or verbs; mark conjunctions and subordinate-clause markers; then identify likely subjects, objects, complements, and prepositional phrases. Next connect articles, nouns, adjectives, pronouns, and participles by agreement.','Treat nonfinite forms as their own small structures. An infinitive may have a governing word and an expressed subject; a participle may have a head noun or relate to a finite verb. When the pieces are visible, produce a provisional reading that preserves the clause relationships. Only then compare an English translation, returning to any place where agreement, voice, or a connector suggests another reading.'],
      recognitionCues:['1. Locate finite verbs and clause markers.','2. Identify subjects, objects, complements, and prepositional phrases.','3. Match agreeing nominals and analyze nonfinite forms.','4. Draft a provisional reading before checking English.'],
      commonFunctions:['Provide a repeatable reading sequence.','Prevent premature dependence on word order or an English translation.','Identify the exact unresolved feature that needs a chart or lexicon.'],
      commonPitfalls:['Do not postpone all sense-making until every word is parsed.','Do not assume the first noun is the subject.','Do not let a familiar English translation override visible Greek relationships.'],
      relatedChartIds:[], relatedArticleIds:['greek-cases-agreement','greek-indicative-system','greek-participles','greek-clause-markers'],
      sources:[organization('merkle-beginning-2020',['Introduction; recurring reading exercises in chs. 1–24'], 'Forms-to-reading progression'), organization('merkle-gems-2019',['ch. 31, “Context”'], 'Context-first interpretive emphasis'), appGuidance('Complete sentence-reading workflow')]
    }),
    article({ id:'greek-selected-syntax', language:'greek', sectionId:'greek-reading', order:20, title:'Selected High-Value Syntax', summary:'A small set of recurring constructions deserves recognition without turning the Handbook into an exhaustive syntax.',
      aliases:['genitive absolute','articular infinitive','predicate nominative','conditional sentence','selected intermediate syntax'], searchTerms:['substantival participle','article adjective position','negation distinctions','purpose result'],
      overview:['Several constructions recur often enough to recognize as units. A predicate nominative is linked to the subject by a copular verb and remains nominative. Article-adjective position helps distinguish modification from predication. An articular infinitive behaves as a nominal phrase and may combine with a preposition. A substantival participle stands where a noun phrase would stand. A genitive absolute normally contributes a circumstance through a genitive participle and its own genitive subject.','Conditional sentences commonly contain a condition and a result, often signaled by εἰ or ἐάν and a corresponding verb form. Purpose and result clauses commonly use recognizable markers, but form and context must be weighed together. These categories are reading aids, not automatic interpretations; the Handbook deliberately omits exhaustive case, conditional, and participial taxonomies.'],
      recognitionCues:['Recognize the construction before assigning a fine-grained label.','Check whether a genitive participle has its own genitive subject.','Read condition marker, mood, and result clause together.'],
      commonFunctions:['Connect subject and predicate.','Package a verbal idea as a noun phrase.','Attach a circumstance to the main clause.','Frame a condition, purpose, or result.'],
      commonPitfalls:['Do not treat every genitive participle as absolute.','Do not assign a conditional class from one particle alone.','Do not turn a useful category into a guaranteed translation.'],
      relatedChartIds:['greek-present-active-participle-lyo','greek-aorist-active-participle-lyo','greek-present-active-infinitive-lyo'], relatedArticleIds:['greek-article-adjectives','greek-infinitives','greek-participles','greek-clause-markers'],
      sources:[organization('merkle-going-2016',['chs. 9–10, 21–24, 29'], 'Selective intermediate categories'), organization('merkle-gems-2019',['chs. 9–10, 21–24, 29'], 'Reading and interpretive value'), appGuidance('Deliberate selection, cautions, and omission of exhaustive taxonomies')]
    }),

    article({ id:'hebrew-nouns-adjectives', language:'hebrew', sectionId:'hebrew-nouns-construct', order:10, title:'Nouns and Adjectives', summary:'Gender, number, state, and agreement work together; endings are clues rather than guarantees.',
      aliases:['noun gender','dual forms','adjective agreement','segolate','irregular noun','nouns and adjectives','Morphology Guide','Parsing Abbreviations'], searchTerms:['masculine plural','feminine plural','lexical gender','vowel reduction','absolute state'],
      overview:['Hebrew nouns have gender and number, and many also contrast absolute and construct state. The endings ־ִים and ־וֹת are common plural clues, while ־ַיִם commonly marks a dual form, but lexical gender and irregular plurals prevent endings from functioning as absolute rules. Learn a noun with its gender and plural whenever possible.','Adjectives agree with the nouns they modify in gender and number and normally in definiteness. An attributive adjective follows its noun and shares definiteness; a predicate adjective commonly stands without the article and contributes the predicate. Segolate and other high-frequency noun patterns may show vowel changes in plural, construct, or suffixed forms. Compare the visible form with its lexical form rather than treating every vowel change as a new root.'],
      recognitionCues:['Check the lexical gender before trusting an ending.','Compare noun and adjective for gender, number, and definiteness.','Expect reduction or stem change when an ending or suffix is added.'],
      commonFunctions:['Identify singular, plural, or dual reference.','Modify a noun attributively or predicate something about it.','Distinguish a lexical stem from its inflected surface shape.'],
      commonPitfalls:['Not every ־וֹת plural is feminine and not every ־ִים plural is masculine.','A predicate adjective need not carry the article.','Segolate and irregular patterns are representative, not productive rules for every noun.'],
      examples:[{ text:'סוּסִים', reference:'Representative', translation:'horses', language:'hebrew' }],
      relatedChartIds:['hebrew-nominal-state-number-endings','hebrew-nominal-segolate-patterns','hebrew-nominal-peculiar-high-frequency'], relatedArticleIds:['hebrew-construct-forms','hebrew-reading-workflow'],
      sources:[organization('pratico-van-pelt-2019',['chs. 4, 7, 10'], 'Noun, adjective, and construct progression'), content('gesenius-1910',['§§80–89; printed pp. 222–247','§§93, 95–96; printed pp. 262–285'], 'Gender, number, state, segolate, and selected irregular patterns','partial'), appGuidance('Lexical-form comparison and agreement checklist')]
    }),
    article({ id:'hebrew-construct-forms', language:'hebrew', sectionId:'hebrew-nouns-construct', order:20, title:'Construct Forms and Construct Chains', summary:'A construct noun is bound to what follows; the chain must be read as one relationship.',
      aliases:['construct chain','construct state','absolute state','definiteness in construct chains'], searchTerms:['of relationship','construct noun','bound form','status constructus'],
      overview:['The construct state binds a noun to a following noun or noun phrase. English often begins with an “of” relationship, but the exact relationship may be possession, material, description, source, or another close connection. The construct noun normally cannot take the definite article or a pronominal suffix because the following element completes it.','Definiteness is normally determined by the final element: a proper name, a suffixed noun, or a definite final noun makes the whole chain definite. Construct forms may be unchanged, may shorten an ending, or may reduce or alter vowels. Long chains should be read from their boundaries: identify each construct link, locate the final absolute element, then refine the relationship from context.'],
      recognitionCues:['Look for a noun immediately bound to another noun without an intervening article.','Check for shortened plural endings or vowel reduction, but allow unchanged constructs.','Locate the final noun before deciding the chain’s definiteness.'],
      commonFunctions:['Express possession, source, material, description, measure, or another close relation.','Create a definite phrase through a definite final element.','Link several nouns into one larger nominal unit.'],
      commonPitfalls:['“Of” is a useful first pass, not the final meaning of every chain.','Do not insert an article on the construct noun.','An unchanged form can still be construct; syntax may be the decisive clue.'],
      examples:[{ text:'דְּבַר יְהוָה', reference:'Jeremiah 1:2', translation:'word of YHWH', language:'hebrew' },{ text:'בְּנֵי יִשְׂרָאֵל', reference:'Exodus 1:1', translation:'sons of Israel', language:'hebrew' }],
      relatedChartIds:['hebrew-nominal-state-number-endings','hebrew-nominal-construct-unchanged','hebrew-nominal-irregular-constructs'], relatedArticleIds:['hebrew-nouns-adjectives','hebrew-pronominal-suffixes','hebrew-reading-workflow'],
      sources:[organization('pratico-van-pelt-2019',['ch. 10'], 'Construct-chain terminology and placement'), content('gesenius-1910',['§89a–e; printed p. 247'], 'Absolute and construct state and representative forms'), appGuidance('Chain-boundary reading workflow')]
    }),
    article({ id:'hebrew-pronominal-suffixes', language:'hebrew', sectionId:'hebrew-suffixes-prepositions', order:10, title:'Pronouns and Pronominal Suffixes', summary:'Identify the base and suffix separately, then read person, gender, and number in context.',
      aliases:['pronominal suffix','object suffix','possessive suffix','person gender number','suffix stems'], searchTerms:['independent pronoun','noun suffix','verb suffix','singular noun base','plural noun base'],
      overview:['Independent personal pronouns can supply or emphasize a subject, especially where the verbal form already marks person, gender, and number. Pronominal suffixes attach to nouns, prepositions, and verbs. On nouns they commonly express a possessive or closely related genitive idea; on verbs they can mark an object; on prepositions they supply the preposition’s complement.','The visible base may change before a suffix is attached. Singular nouns, plural nouns, and feminine nouns can use different suffix stems, and a plural-looking base before a suffix does not necessarily make the possessed noun plural unless the paradigm supports it. Verbal object-suffix coverage in the current charts is deliberately limited to directly printed examples.'],
      recognitionCues:['Separate the suffix from the base before assigning a gloss.','Parse suffix person, gender, and number independently from the host word.','Compare the base with the correct noun, preposition, or verb chart family.'],
      commonFunctions:['Express possession or another genitive relation on nouns.','Supply the object of a preposition.','Mark a pronominal object on a verb.'],
      commonPitfalls:['The suffix describes its referent, not the gender or number of the host noun.','Not all nouns use one identical suffix base.','The five verbal examples do not constitute a complete object-suffix system.'],
      examples:[{ text:'עַמִּי', reference:'Exodus 3:10', translation:'my people', language:'hebrew' },{ text:'סוּסוֹ', reference:'Representative', translation:'his horse', language:'hebrew' }],
      relatedChartIds:['hebrew-noun-suffix-singular-av','hebrew-noun-suffix-plural-banim','hebrew-noun-suffix-feminine-comparison','hebrew-verbal-object-suffix-perfect-examples'], relatedArticleIds:['hebrew-prepositions-article','hebrew-construct-forms','hebrew-reading-workflow'],
      sources:[organization('pratico-van-pelt-2019',['chs. 8–9, 19'], 'Pronoun and suffix grouping'), content('gesenius-1910',['§§32–33; printed pp. 105–108','§§58–59; printed pp. 155–160','§91; printed pp. 254–259'], 'Pronouns and noun/verbal suffix morphology','partial'), appGuidance('Base-plus-suffix parsing workflow and coverage warnings')]
    }),
    article({ id:'hebrew-prepositions-article', language:'hebrew', sectionId:'hebrew-suffixes-prepositions', order:20, title:'Prepositions, the Article, and Attached Forms', summary:'Read inseparable prepositions and the article as attached morphology, then recover the base relationship.',
      aliases:['inseparable prepositions','preposition plus article','min assimilation','מִן','definite article','particles and prepositions'], searchTerms:['בְּ','כְּ','לְ','וְ','attached prefix','prepositional suffix'],
      overview:['The inseparable prepositions בְּ, כְּ, and לְ attach directly to a following word. When they combine with the definite article, the article’s ה normally disappears while its vowel and the expected doubling remain when the consonant permits. The preposition מִן may appear independently or assimilate its nun into the following consonant, commonly signaled by doubling.','Prepositions with pronominal suffixes do not all use the same base. Some attach directly; others use an altered or plural-like base. The current charts therefore show selected common families separately. Identify every prefix and suffix before treating the middle of the word as a lexical root, and confirm apparent article behavior against the following consonant.'],
      recognitionCues:['Test for inseparable preposition plus article when a prefix has an article-like vowel.','Look for compensatory behavior when doubling is not possible.','Choose the correct prepositional base before reading a suffix.'],
      commonFunctions:['Mark location, direction, comparison, means, source, or relation.','Combine a preposition with a definite noun phrase.','Take a pronominal complement through a suffix.'],
      commonPitfalls:['Do not peel off every initial letter as a prefix without checking the lexeme.','Do not assume every preposition receives suffixes directly.','A missing visible ה does not mean the phrase is indefinite after contraction.'],
      examples:[{ text:'בַּבַּיִת', reference:'Representative', translation:'in the house', language:'hebrew' }],
      relatedChartIds:['hebrew-preposition-suffix-lamed','hebrew-preposition-suffix-min','hebrew-preposition-suffix-el','hebrew-preposition-suffix-al'], relatedArticleIds:['hebrew-pronominal-suffixes','hebrew-clause-markers','hebrew-reading-workflow'],
      sources:[organization('pratico-van-pelt-2019',['chs. 5–6, 9'], 'Article, preposition, and suffix sequence'), content('gesenius-1910',['§35; printed pp. 110–112','§§102–103; printed pp. 298–305'], 'Article/preposition combination, assimilation, and selected suffix bases','partial'), appGuidance('Attachment-first parsing procedure')]
    }),
    article({ id:'hebrew-qal-finite', language:'hebrew', sectionId:'hebrew-qal-conjugations', order:10, title:'The Qal Stem and Finite Conjugations', summary:'Use the Qal strong verb as a baseline for root, stem, person, gender, number, and conjugation.',
      aliases:['Qal','Qal perfect','Qal imperfect','Hebrew conjugations','suffix conjugation','prefix conjugation'], searchTerms:['root stem','perfect imperfect','lexical root','surface form','person gender number'],
      overview:['Hebrew verbs are organized around a lexical root and a stem pattern. Qal is the basic or simple stem and provides the first comparison point, but the lexical meaning of each root must still be learned. Finite forms mark person, gender, and number through suffixes, prefixes, and sometimes both. The perfect is often called the suffix conjugation because its person marking is especially visible at the end; the imperfect is often called the prefix conjugation because its person marker begins the form.','Perfect and imperfect do not function as simple equivalents of English past and future. They present different verbal forms whose time and discourse contribution depend on clause type and context. Begin with root, stem, and person/gender/number; then ask how the form functions in the clause and verbal sequence.'],
      recognitionCues:['Find the prefix and suffix before proposing the three root consonants.','Compare the visible form with the strong Qal model קָטַל / יִקְטֹל.','Use pointing and the whole pattern, not consonants alone, to confirm the stem.'],
      commonFunctions:['Perfect commonly presents a bounded or complete situation in many contexts.','Imperfect commonly presents an incomplete, projected, repeated, modal, or future-oriented situation in many contexts.','Both participate in larger clause and sequence patterns.'],
      commonPitfalls:['Do not translate perfect mechanically as past or imperfect mechanically as future.','Qal is not guaranteed to be active for every lexical root.','A surface form may hide or alter a weak radical.'],
      examples:[{ text:'קָטַל', reference:'Gesenius Paradigm B', translation:'Qal perfect strong-verb model', language:'hebrew' },{ text:'יִקְטֹל', reference:'Gesenius Paradigm B', translation:'Qal imperfect strong-verb model', language:'hebrew' }],
      relatedChartIds:['hebrew-strong-qal-perfect','hebrew-strong-qal-imperfect'], relatedArticleIds:['hebrew-qal-volitives-nonfinite','hebrew-derived-stem-recognition','hebrew-sequential-forms'],
      sources:[organization('pratico-van-pelt-2019',['chs. 12–16'], 'Qal-first strong/weak and perfect/imperfect sequence'), content('gesenius-1910',['§§43–47; printed pp. 118–128','Paradigm B, printed pp. 510–511'], 'Qal finite morphology and terminology'), appGuidance('Root-stem-PGN-clause reading order and tense cautions')]
    }),
    article({ id:'hebrew-qal-volitives-nonfinite', language:'hebrew', sectionId:'hebrew-qal-conjugations', order:20, title:'Qal Commands, Infinitives, and Participles', summary:'Recognize volitive and nonfinite forms through their shape and their relationship to the clause.',
      aliases:['imperative cohortative jussive','infinitive construct','infinitive absolute','Qal participle','nonfinite'], searchTerms:['command','volitive','participle','verbal noun','shortened imperfect'],
      overview:['The imperative addresses a second person; the cohortative commonly marks a first-person volitive; the jussive commonly marks a third-person or sometimes second-person volitive and may use a shortened imperfect form. Not every jussive is visibly distinct, so negation, clause setting, and context matter. The current Paradigm Charts provide directly sourced imperative and shortened-form anchors but do not invent missing systems.','The infinitive construct behaves as a verbal noun and frequently follows a preposition or governs its own complements. The infinitive absolute can emphasize or otherwise qualify a verbal idea in established constructions. The participle behaves like a verbal adjective and commonly presents an ongoing activity, characteristic role, or state; it agrees for gender and number.'],
      recognitionCues:['Use person and clause context to distinguish imperative, cohortative, and jussive force.','Look for prefixed לְ with an infinitive construct, while allowing other constructions.','Treat a participle as both verbal and adjectival.'],
      commonFunctions:['Express command, desire, resolve, or appeal.','Package a verbal idea with an infinitive construct.','Emphasize or qualify a verb with an infinitive absolute.','Describe ongoing activity or a characteristic participant with a participle.'],
      commonPitfalls:['Not every jussive has a unique visible form.','Do not assume לְ always marks an infinitive; inspect the base.','A participle’s English tense depends on context.'],
      relatedChartIds:['hebrew-strong-qal-imperative','hebrew-strong-qal-infinitive-construct','hebrew-strong-qal-infinitive-absolute','hebrew-strong-qal-participle'], relatedArticleIds:['hebrew-qal-finite','hebrew-clause-markers','hebrew-reading-workflow'],
      sources:[organization('pratico-van-pelt-2019',['chs. 18, 20–22'], 'Imperative, infinitive, and participle sequence'), content('gesenius-1910',['§§45–46; printed pp. 122–125','§48; printed pp. 129–131','§50; printed p. 136','Paradigm B, printed p. 510'], 'Qal volitive and nonfinite morphology','partial'), appGuidance('Clause-context recognition procedure')]
    }),
    article({ id:'hebrew-derived-stem-recognition', language:'hebrew', sectionId:'hebrew-derived-stems', order:10, title:'Recognizing the Derived Stems', summary:'Stem prefixes, vowels, and doubling provide recognition clues; the lexicon and context determine meaning.',
      aliases:['Niphal','Piel','Pual','Hiphil','Hophal','Hithpael','Hitpael','derived stems','stem meanings'], searchTerms:['binyanim','causative','passive','reflexive','dagesh'],
      overview:['The major derived stems are Niphal, Piel, Pual, Hiphil, Hophal, and Hitpael. Niphal often has נ or its assimilated effect; Piel and Pual commonly show characteristic vowels and doubling of the middle radical; Hiphil and Hophal commonly show an ה prefix in several forms; Hitpael commonly shows הת and middle-radical doubling. These cues vary across conjugations and weak roots, so compare the whole pointed pattern with the relevant chart.','Stem labels describe morphology before they describe meaning. Niphal often has passive or reflexive relationships, Piel and Pual often form an active/passive pair, Hiphil and Hophal often form a causative active/passive pair, and Hitpael often has reflexive or reciprocal force. None of these tendencies is an automatic gloss. A root may develop a conventional meaning in a stem that must be learned lexically.'],
      recognitionCues:['Identify any stem prefix, then check vowels and middle-radical doubling.','Compare the same conjugation across the strong-stem charts.','If the pattern is distorted, test for weak-root behavior after proposing the stem.'],
      commonFunctions:['Niphal: often passive, reflexive, or result-oriented.','Piel/Pual: often an active/passive relationship with factitive, resultative, or other lexical development.','Hiphil/Hophal: often causative active/passive.','Hitpael: often reflexive, reciprocal, or iterative.'],
      commonPitfalls:['Piel does not always mean intensive.','Hiphil does not always mean causative.','Niphal does not always mean passive.','The lexical entry and clause context outrank a memorized stem gloss.'],
      relatedChartIds:['hebrew-strong-niphal-perfect','hebrew-strong-piel-perfect','hebrew-strong-pual-perfect','hebrew-strong-hiphil-perfect','hebrew-strong-hophal-perfect','hebrew-strong-hitpael-perfect'], relatedArticleIds:['hebrew-qal-finite','hebrew-weak-overview','hebrew-reading-workflow'],
      sources:[organization('pratico-van-pelt-2019',['chs. 24–35'], 'Strong/weak derived-stem sequence and modern labels'), content('gesenius-1910',['§§51–54; printed pp. 137–151','Paradigm B, printed pp. 510–511'], 'Derived-stem morphology and broad relationships','partial'), appGuidance('Pattern-first recognition and semantic cautions')]
    }),
    article({ id:'hebrew-weak-overview', language:'hebrew', sectionId:'hebrew-weak-verbs', order:10, title:'How Weak Verbs Change', summary:'Weak verbs are read by comparing the visible form with a strong pattern and locating the affected radical.',
      aliases:['weak verb','weak roots','disappearing consonant','assimilation','guttural behavior'], searchTerms:['vowel clues','lexical root','surface form','strong pattern'],
      overview:['A weak verb contains a radical whose behavior changes the expected strong pattern. A consonant may disappear, assimilate, resist doubling, or trigger a vowel change. The lexical root therefore may not be fully visible on the surface. Weakness is positional: the first, second, or third radical may cause a different family of changes, and more than one weak feature can occur in one root.','Recognition is more stable than memorizing isolated forms. First propose the stem and conjugation. Next identify the expected strong pattern and compare it with the visible form. Ask which radical is missing or altered, whether a guttural blocks doubling, whether nun has assimilated, or whether a hollow or final-he pattern explains the vowels. Then consult the exact weak-family chart.'],
      recognitionCues:['Identify stem and conjugation before naming the weak class.','Compare expected and visible radicals position by position.','Use doubling and vowel length as evidence for assimilation or contraction.'],
      commonFunctions:['Recover a lexical root from an altered surface form.','Distinguish stem morphology from weak-root change.','Choose a focused comparison chart instead of guessing by analogy.'],
      commonPitfalls:['A missing consonant is not necessarily absent from the lexical root.','One unusual vowel does not identify a weak class by itself.','Doubly weak and irregular examples are not complete productive paradigms.'],
      relatedChartIds:['hebrew-weak-pe-nun-qal-imperfect-nagash','hebrew-weak-hollow-ayin-waw-qal-perfect-qum','hebrew-weak-lamed-he-qal-perfect-galah'], relatedArticleIds:['hebrew-weak-classes','hebrew-derived-stem-recognition','hebrew-reading-workflow'],
      sources:[organization('pratico-van-pelt-2019',['chs. 14, 16, 25, 27, 29, 31, 33, 35'], 'Strong-versus-weak comparison sequence'), content('gesenius-1910',['§§62–78; printed pp. 164–219','Paradigms D–P, printed pp. 514–529'], 'Weak-root behavior and directly represented forms','partial'), appGuidance('Expected-versus-visible comparison workflow')]
    }),
    article({ id:'hebrew-weak-classes', language:'hebrew', sectionId:'hebrew-weak-verbs', order:20, title:'Weak-Root Families', summary:'Positional class labels tell the reader where to look for a change; subtypes remain distinct where they aid recognition.',
      aliases:['I-Nun','III-He','hollow verb','geminate','I-Yod','I-Guttural','II-Guttural','III-ח/ע','doubly weak','irregular'], searchTerms:['Biconsonantal Middle Waw Yod','Pe-nun','Lamed-he','weak class'],
      overview:['The Handbook uses the established visible labels I-Guttural, II-Guttural, III-ח/ע, I-Nun, I-Yod, Biconsonantal—Middle Waw/Yod, Geminate, III-He, Doubly Weak, and Irregular. The labels identify the affected radical position or the form of the root. They are navigation aids, not claims that every root in a family behaves identically.','I-Nun frequently loses or assimilates nun in prefix forms. I-Yod includes historically distinct patterns that remain visible in the charts. Biconsonantal Middle Waw/Yod roots often show contracted vowel patterns; Geminate roots have matching second and third radicals. III-He roots frequently alter or lose the final radical. Gutturals resist ordinary doubling and influence nearby vowels. Doubly Weak and Irregular coverage remains limited to directly sourced examples.'],
      recognitionCues:['I-Nun: look for missing nun and doubling of the following radical.','Biconsonantal Middle Waw/Yod: look for a long vowel where a middle radical is not visible.','Geminate: look for contraction or doubled matching radicals.','III-He: compare the final radical across conjugations and endings.'],
      commonFunctions:['Select the right weak-family chart.','Preserve distinctions between historical I-Waw and true I-Yod or Middle Waw and Middle Yod.','Recognize when multiple weak features limit prediction.'],
      commonPitfalls:['Do not rename or collapse stable weak-class IDs.','Do not infer a complete III-Aleph or doubly weak system from neighboring charts.','A class label does not replace root-specific lexical knowledge.'],
      relatedChartIds:['hebrew-weak-initial-guttural-qal-imperfect-amad','hebrew-weak-pe-nun-qal-wayyiqtol-naphal','hebrew-weak-pe-yod-waw-qal-imperfect-yashav','hebrew-weak-geminate-qal-perfect-savav','hebrew-weak-doubly-weak-qal-wayyiqtol-hayah'], relatedArticleIds:['hebrew-weak-overview','hebrew-sequential-forms'],
      sources:[organization('pratico-van-pelt-2019',['weak-verb chapters paired with chs. 14, 16, 25, 27, 29, 31, 33, 35'], 'Visible positional terminology and grouping'), content('gesenius-1910',['§§62–78; printed pp. 164–219','Paradigms D–P, printed pp. 514–529'], 'Weak forms and historical/morphological distinctions','partial'), appGuidance('Concise class recognition cues and explicit omissions')]
    }),
    article({ id:'hebrew-clause-structure', language:'hebrew', sectionId:'hebrew-reading', order:10, title:'Verbal and Verbless Clauses', summary:'Locate the predicate first, then use definiteness, agreement, and context rather than one rigid word-order rule.',
      aliases:['sentence syntax','verbal clause','verbless clause','nominal clause','word order'], searchTerms:['subject predicate','definiteness','predicate adjective','construct relationships'],
      overview:['A verbal clause has a finite verb as its predicate. A verbless clause has a nominal, adjective, participle, or prepositional phrase serving as predicate, with a present-tense form of “to be” often supplied in English. In both types, agreement, definiteness, and discourse context help distinguish subject from predicate.','Verb-first order is common in Biblical Hebrew narrative, but subjects, objects, and other elements may be placed first for discourse reasons. A definite nominal is often a strong subject candidate in a verbless clause, while an indefinite adjective or noun may serve as predicate; this is a reading clue, not an inflexible law. Construct chains and article-adjective relationships should be identified before clause roles are assigned.'],
      recognitionCues:['Ask whether the clause has a finite verb; if not, identify the likely nominal predicate.','Use definiteness and agreement as evidence, not as isolated rules.','Mark construct chains and prepositional phrases before assigning subject and predicate.'],
      commonFunctions:['Make an assertion with a finite verb.','Express identity, quality, location, or possession in a verbless clause.','Front a constituent for discourse or contextual reasons.'],
      commonPitfalls:['Do not impose one Hebrew word order on every clause.','Do not insert an English copula until the Hebrew relationship is clear.','Definiteness is a clue, not a universal subject test.'],
      relatedChartIds:[], relatedArticleIds:['hebrew-nouns-adjectives','hebrew-construct-forms','hebrew-sequential-forms','hebrew-reading-workflow'],
      sources:[organization('pratico-van-pelt-2019',['ch. 23, “Sentence Syntax”'], 'Introductory clause framework'), content('gesenius-1910',['§§140–142; printed pp. 450–457'], 'Foundational verbal and nominal clause observations','partial'), appGuidance('Predicate-first and evidence-based word-order procedure')]
    }),
    article({ id:'hebrew-sequential-forms', language:'hebrew', sectionId:'hebrew-reading', order:20, title:'Waw and Sequential Verbal Forms', summary:'Wayyiqtol is a distinct visible narrative form; waw with other forms must be read from morphology and sequence.',
      aliases:['wayyiqtol','waw consecutive','waw-consecutive','waw plus verbal forms','sequential form'], searchTerms:['narrative sequence','וַי','consecutive imperfect','coordination'],
      overview:['The form commonly called wayyiqtol combines prefixed waw with an imperfect-related form and commonly advances a past narrative sequence. The visible וַי pattern and doubling of the prefix consonant, where spelling permits, are important clues. The current charts contain only the directly printed Qal and Hiphil recognition examples; they do not generate a complete paradigm.','Not every waw before a verb creates wayyiqtol. Waw may coordinate clauses before perfect, imperfect, imperative, cohortative, jussive, participial, or other forms. Identify the verbal morphology after waw and consider the surrounding sequence. Older “waw-consecutive” terminology remains searchable, but the Handbook avoids suggesting that waw mechanically reverses tense.'],
      recognitionCues:['Look for וַ plus an imperfect prefix and expected doubling when possible.','Distinguish wayyiqtol from simple וְ coordination before another verbal form.','Read the form inside the larger verbal sequence.'],
      commonFunctions:['Advance events in narrative.','Coordinate a new clause with the preceding discourse.','Link verbal forms whose contribution depends on sequence and context.'],
      commonPitfalls:['Waw does not mechanically change past into future or future into past.','Do not call every waw-prefixed verb wayyiqtol.','A recognition anchor is not a complete person paradigm.'],
      examples:[{ text:'וַיֹּאמֶר', reference:'Genesis 1:3', translation:'and he said', language:'hebrew' }],
      relatedChartIds:['hebrew-strong-qal-wayyiqtol','hebrew-strong-hiphil-wayyiqtol','hebrew-weak-pe-nun-qal-wayyiqtol-naphal'], relatedArticleIds:['hebrew-qal-finite','hebrew-weak-classes','hebrew-clause-structure','hebrew-reading-workflow'],
      sources:[organization('pratico-van-pelt-2019',['ch. 17, “Waw Consecutive”'], 'Familiar classroom location and searchable terminology'), content('gesenius-1910',['§49b–c; printed pp. 133–134'], 'Directly printed consecutive-imperfect description and examples','partial'), appGuidance('Sequential-form distinction and anti-reversal caution')]
    }),
    article({ id:'hebrew-clause-markers', language:'hebrew', sectionId:'hebrew-reading', order:30, title:'Clause Markers, Negation, and Relative Clauses', summary:'Particles and attached prefixes mark coordination, negation, and subordination before the whole clause is translated.',
      aliases:['לֹא','אַל','relative clause','אֲשֶׁר','waw coordination','subordinate clause'], searchTerms:['negation','relative marker','conjunction','particles'],
      overview:['The conjunction וְ commonly coordinates words or clauses, while its precise discourse contribution depends on what follows. לֹא commonly negates statements and many ordinary verbal forms; אַל commonly appears with prohibitions and jussive-related forms. These are strong recognition tendencies, but the whole construction should be checked.','The relative marker אֲשֶׁר introduces a clause that describes or identifies an antecedent. Hebrew relative clauses may rely on a resumptive pronoun, suffix, or adverb inside the clause where English uses only a relative word. Other particles and conjunctions introduce temporal, causal, conditional, or content relationships, but the Handbook limits itself to identifying the boundary and reading the relationship from context.'],
      recognitionCues:['Mark וְ, לֹא, אַל, and אֲשֶׁר before parsing the clause interior.','Read negation with the following verbal form.','Look inside a relative clause for a suffix or pronoun that resumes the antecedent.'],
      commonFunctions:['Coordinate clauses or phrases.','Negate an assertion or express a prohibition.','Attach a relative description to an antecedent.','Introduce an elementary subordinate relationship.'],
      commonPitfalls:['Do not treat every וְ as simple chronological “and then.”','Do not interchange לֹא and אַל mechanically.','Do not expect Hebrew relative clauses to mirror English word for word.'],
      relatedChartIds:[], relatedArticleIds:['hebrew-prepositions-article','hebrew-qal-volitives-nonfinite','hebrew-sequential-forms','hebrew-reading-workflow'],
      sources:[organization('pratico-van-pelt-2019',['chs. 5, 18, 23'], 'Conjunction, volitive, and sentence-syntax placement'), content('gesenius-1910',['§152; printed p. 478','§155; printed p. 485'], 'Negation and relative-clause foundations','partial'), appGuidance('Clause-boundary and resumptive-element checklist')]
    }),
    article({ id:'hebrew-reading-workflow', language:'hebrew', sectionId:'hebrew-reading', order:40, title:'A Workflow for Reading Hebrew Clauses', summary:'Observe boundaries and attached morphology, propose the root and stem, then produce a provisional reading.',
      aliases:['reading Hebrew clauses','Hebrew sentence workflow','reading workflow'], searchTerms:['clause boundaries','prefix suffix','root stem','weak root','provisional reading'],
      overview:['Begin by marking clause boundaries and conjunctions. Locate a finite verb or, in a verbless clause, the likely predicate. Separate inseparable prefixes and pronominal suffixes from their host. Identify construct chains and adjective relationships before assigning broader clause roles. Then parse person, gender, and number and propose the lexical root and stem.','If the form differs from the strong pattern, inspect it for weak-root behavior rather than guessing from one vowel. Consult the focused Paradigm Chart only after observing the visible clues. Finally produce a provisional reading that preserves the clause relationships, verbal sequence, and attached elements. Compare English afterward and revisit the exact feature that remains uncertain.'],
      recognitionCues:['1. Mark clause boundaries and locate the verb or predicate.','2. Separate prefixes and suffixes; identify construct and adjective relationships.','3. Parse person, gender, and number; propose root and stem.','4. Inspect weak-root behavior, consult a chart, and draft a provisional reading.'],
      commonFunctions:['Provide one repeatable order for clause analysis.','Keep morphology connected to syntax and discourse.','Delay English comparison until the Hebrew structure has been observed.'],
      commonPitfalls:['Do not propose a root before separating common attachments.','Do not impose verb-first order on every clause.','Do not let a chart substitute for reading the surrounding sequence.'],
      relatedChartIds:[], relatedArticleIds:['hebrew-construct-forms','hebrew-pronominal-suffixes','hebrew-qal-finite','hebrew-weak-overview','hebrew-sequential-forms'],
      sources:[organization('pratico-van-pelt-2019',['chs. 12–23 and recurring diagnostics'], 'Progression from noun attachments to verb systems and sentence syntax'), appGuidance('Complete Hebrew clause-reading workflow')]
    })
  ]);

  const normalize = value => String(value ?? '').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  const articleText = item => [item.id,item.title,item.summary,...item.aliases,...item.searchTerms,...item.overview,...item.recognitionCues,...item.commonFunctions,...item.commonPitfalls,...item.examples.flatMap(example=>[example.text,example.reference,example.translation])].join(' ');
  function sectionsForLanguage(language){ return sections.filter(section=>section.language===language).sort((a,b)=>a.order-b.order); }
  const sectionOrder = sectionId => sections.find(section=>section.id===sectionId)?.order ?? 999;
  function articlesForLanguage(language){ return articles.filter(item=>item.language===language).sort((a,b)=>sectionOrder(a.sectionId)-sectionOrder(b.sectionId)||a.order-b.order); }
  function articlesForSection(sectionId){ return articles.filter(item=>item.sectionId===sectionId).sort((a,b)=>a.order-b.order); }
  function getArticle(id){ return articles.find(item=>item.id===id) || null; }
  function searchArticles(query='', language='all', sectionId=''){
    const needle=normalize(String(query).trim());
    return articles.filter(item=>(language==='all'||item.language===language)&&(!sectionId||item.sectionId===sectionId)&&(!needle||normalize(articleText(item)).includes(needle)))
      .sort((a,b)=>sectionOrder(a.sectionId)-sectionOrder(b.sectionId)||a.order-b.order);
  }
  function articlesForChart(chartId){ return articles.filter(item=>item.relatedChartIds.includes(chartId)); }
  function sourceForId(id){ return sources[id] || null; }

  const api=Object.freeze({ sources, sections, articles, sectionsForLanguage, articlesForLanguage, articlesForSection, getArticle, searchArticles, articlesForChart, sourceForId });
  if(typeof module!=='undefined'&&module.exports) module.exports=api;
  root.PuritanHandbookData=api;
})(typeof window!=='undefined'?window:globalThis);
