/* ---------- Grammar & Reference Library Data ---------- */
(function(root){
  const topics = [
    { id:'greek-articles', language:'greek', title:'Articles', category:'Nominals', summary:'The Greek article marks case, number, and gender and often identifies a noun as definite or previously known.', body:['The article agrees with its noun in case, number, and gender. Translate it often as “the,” but watch for substantival use where the article turns an adjective, participle, or phrase into a noun-like expression.','Articles are also useful parsing anchors: if you can parse the article, you usually know the noun pattern nearby.'], charts:[{label:'Common article forms', columns:['Case','Masculine','Feminine','Neuter'], rows:[['Nom sg','ὁ','ἡ','τό'],['Gen sg','τοῦ','τῆς','τοῦ'],['Dat sg','τῷ','τῇ','τῷ'],['Acc sg','τόν','τήν','τό'],['Nom pl','οἱ','αἱ','τά'],['Gen pl','τῶν','τῶν','τῶν'],['Dat pl','τοῖς','ταῖς','τοῖς'],['Acc pl','τούς','τάς','τά']]}], examples:[{text:'ὁ λόγος', note:'the word — nominative masculine singular'},{text:'τὰ ἔργα', note:'the works — nominative/accusative neuter plural'}], related:['greek-noun-paradigms','greek-adjective-paradigms','greek-pronouns'] },
    { id:'greek-pronouns', language:'greek', title:'Pronouns', category:'Nominals', summary:'Pronouns replace or point to nouns and are parsed for case, number, gender, and sometimes person.', body:['Koine pronouns include personal, demonstrative, relative, interrogative, and indefinite forms. Pronouns must be read in context because their antecedent may be nearby or implied.','Personal pronouns emphasize person; demonstratives such as οὗτος and ἐκεῖνος often point to something in the discourse.'], charts:[{label:'Personal pronoun snapshots', columns:['Person','Nominative','Genitive','Accusative'], rows:[['1 sg','ἐγώ','μου / ἐμοῦ','με / ἐμέ'],['2 sg','σύ','σου / σοῦ','σε / σέ'],['3 masc sg','αὐτός','αὐτοῦ','αὐτόν']]}], examples:[{text:'αὐτὸς λέγει', note:'he himself says'},{text:'ὃς ἔχει ὦτα', note:'the one who has ears'}], related:['greek-articles','greek-noun-paradigms'] },
    { id:'greek-noun-paradigms', language:'greek', title:'Noun paradigms', category:'Nominals', summary:'Greek nouns decline by case and number, with gender usually belonging to the lexical item.', body:['Nouns are parsed by case, number, and gender. Case often signals function: nominative for subject, genitive for possession or source, dative for indirect object or means, accusative for direct object, and vocative for address.','First, second, and third declension labels describe form patterns, not meaning.'], charts:[{label:'Second declension masculine: λόγος', columns:['Case','Singular','Plural'], rows:[['Nom','λόγος','λόγοι'],['Gen','λόγου','λόγων'],['Dat','λόγῳ','λόγοις'],['Acc','λόγον','λόγους'],['Voc','λόγε','λόγοι']]}], examples:[{text:'βλέπει τὸν λόγον', note:'accusative λόγον functions as direct object'},{text:'φωνὴ κυρίου', note:'genitive κυρίου can express possession/source'}], related:['greek-articles','greek-adjective-paradigms'] },
    { id:'greek-adjective-paradigms', language:'greek', title:'Adjective paradigms', category:'Nominals', summary:'Greek adjectives agree with the nouns they modify in case, number, and gender.', body:['Adjectives may be attributive (“the good word”), predicate (“the word is good”), or substantival (“the good [one]”). The article position often helps distinguish attributive and predicate uses.','Many common adjectives follow 2-1-2 endings; others follow 3-3 or mixed patterns.'], charts:[{label:'2-1-2 adjective: ἀγαθός', columns:['Gender','Nom sg','Acc sg','Nom pl'], rows:[['Masc','ἀγαθός','ἀγαθόν','ἀγαθοί'],['Fem','ἀγαθή','ἀγαθήν','ἀγαθαί'],['Neut','ἀγαθόν','ἀγαθόν','ἀγαθά']]}], examples:[{text:'ὁ ἀγαθὸς λόγος', note:'attributive: the good word'},{text:'ἀγαθὸς ὁ λόγος', note:'predicate: the word is good'}], related:['greek-articles','greek-noun-paradigms'] },
    { id:'greek-verb-overview', language:'greek', title:'Verb overview', category:'Verbs', summary:'Greek verbs communicate action or state through tense-form, voice, mood, person, and number.', body:['A finite Greek verb is usually parsed for tense-form, voice, mood, person, and number. Non-finite forms such as infinitives and participles have different parsing needs.','Start with the big three: tense-form describes aspect/time, voice describes subject relationship to the action, and mood describes how the action is presented.'], charts:[{label:'Main parsing categories', columns:['Category','Question it answers'], rows:[['Tense-form','What kind of action/viewpoint?'],['Voice','How is the subject related to the action?'],['Mood','How is the action presented?'],['Person/number','Who performs or is associated with the verb?']]}], examples:[{text:'λύει', note:'present active indicative, 3rd singular'},{text:'πιστεύωμεν', note:'present active subjunctive, 1st plural'}], related:['greek-tense-explanations','greek-voice-explanations','greek-mood-explanations'] },
    { id:'greek-tense-explanations', language:'greek', title:'Tense explanations', category:'Verbs', summary:'Greek tense-forms combine aspect with time most clearly in the indicative mood.', body:['Present and imperfect usually present imperfective aspect. Aorist usually presents perfective aspect. Perfect and pluperfect usually emphasize a resulting state. Future often points forward.','Do not reduce every tense-form to English time. In non-indicative moods, aspect is often more important than time.'], charts:[{label:'Greek tense-form overview', columns:['Tense-form','Typical force'], rows:[['Present','ongoing/imperfective'],['Imperfect','past ongoing/imperfective'],['Aorist','summary/perfective'],['Perfect','completed with present result'],['Future','future-oriented'],['Pluperfect','past state from prior action']]}], examples:[{text:'ἔλυσεν', note:'aorist: viewed as a complete event'},{text:'λέγει', note:'present: action viewed as in progress or generally true'}], related:['greek-verb-overview','greek-voice-explanations','greek-mood-explanations'] },
    { id:'greek-voice-explanations', language:'greek', title:'Voice explanations', category:'Verbs', summary:'Voice describes the subject’s relationship to the action: active, middle, passive, or middle/passive by form.', body:['Active voice normally presents the subject as doing the action. Passive presents the subject as acted upon. Middle often highlights the subject’s participation, interest, or involvement.','Some forms are morphologically middle/passive and must be interpreted by context.'], charts:[{label:'Voice overview', columns:['Voice','Basic idea'], rows:[['Active','subject acts'],['Middle','subject participates with special involvement'],['Passive','subject receives action'],['Middle/passive','form requires contextual decision']]}], examples:[{text:'λύει', note:'he/she/it looses'},{text:'λύεται', note:'he/she/it is loosed or acts with middle force, depending on context'}], related:['greek-verb-overview','greek-tense-explanations','greek-mood-explanations'] },
    { id:'greek-mood-explanations', language:'greek', title:'Mood explanations', category:'Verbs', summary:'Mood presents the action as assertion, possibility, command, verbal idea, or adjectival verbal form.', body:['Indicative normally states or asks about reality. Subjunctive often presents potential, exhortation, or purpose. Imperative commands. Infinitives function as verbal nouns, and participles function as verbal adjectives.','Optative is less common in the New Testament but may express wish or possibility.'], charts:[{label:'Mood overview', columns:['Mood','Common use'], rows:[['Indicative','statement/question'],['Subjunctive','potential, purpose, exhortation'],['Imperative','command'],['Infinitive','verbal noun'],['Participle','verbal adjective'],['Optative','wish/possibility']]}], examples:[{text:'λέγει', note:'indicative: he says'},{text:'λέγετε', note:'imperative or indicative depending on form/context'}], related:['greek-verb-overview','greek-tense-explanations','greek-voice-explanations'] },
    { id:'hebrew-pronouns', language:'hebrew', title:'Pronouns', category:'Nominals', summary:'Hebrew pronouns mark person, gender, and number and may stand alone or attach as suffixes.', body:['Independent pronouns often supply emphasis or serve as subjects in verbless clauses. Pronominal suffixes can attach to nouns, prepositions, and verbs.','Because Biblical Hebrew often encodes subject information in the verb, an explicit pronoun can be emphatic.'], charts:[{label:'Independent pronoun snapshots', columns:['Person','Singular','Plural'], rows:[['1 common','אֲנִי / אָנֹכִי','אֲנַחְנוּ'],['2 masculine','אַתָּה','אַתֶּם'],['2 feminine','אַתְּ','אַתֶּן'],['3 masculine','הוּא','הֵם'],['3 feminine','הִיא','הֵנָּה']]}], examples:[{text:'אֲנִי יְהוָה', note:'I am YHWH'},{text:'סוּסוֹ', note:'his horse, with 3ms suffix'}], related:['hebrew-noun-basics'] },
    { id:'hebrew-noun-basics', language:'hebrew', title:'Noun patterns / noun basics', category:'Nominals', summary:'Hebrew nouns have gender, number, and state; construct chains are central to noun syntax.', body:['Hebrew nouns are usually masculine or feminine, singular or plural, and absolute or construct. The construct state links one noun closely to a following noun, often translated with “of.”','Plural endings are common clues, but noun gender and plural patterns are not always predictable.'], charts:[{label:'Noun basics', columns:['Feature','Common markers'], rows:[['Masculine plural','־ִים'],['Feminine singular','־ָה / ־ת'],['Feminine plural','־וֹת'],['Construct','bound form before another noun']]}], examples:[{text:'דְּבַר יְהוָה', note:'word of YHWH — construct chain'},{text:'סוּסִים', note:'horses — common masculine plural ending'}], related:['hebrew-pronouns'] },
    ...['Qal','Niphal','Piel','Pual','Hiphil','Hophal','Hitpael'].map(stem => ({ id:`hebrew-${stem.toLowerCase()}`, language:'hebrew', title:stem, category:'Verbal stems', summary:`${stem} is one of the major Biblical Hebrew verbal stems (binyanim).`, body:[stem==='Qal'?'Qal is the basic/light stem and often carries the simple lexical meaning of the verb.':`${stem} modifies the basic verbal idea in a conventional stem pattern; exact meaning depends on the root and context.`,'Learn stem recognition from both prefixes/suffixes and vowel patterns, but confirm meaning from the lexicon and context.'], charts:[{label:`${stem} quick profile`, columns:['Stem','Typical value','Example'], rows:[[stem, {Qal:'simple active/stative',Niphal:'simple passive or reflexive',Piel:'intensive/factitive active',Pual:'Piel passive',Hiphil:'causative active',Hophal:'Hiphil passive',Hitpael:'reflexive/reciprocal/intensive'}[stem], {Qal:'קָטַל',Niphal:'נִקְטַל',Piel:'קִטֵּל',Pual:'קֻטַּל',Hiphil:'הִקְטִיל',Hophal:'הָקְטַל',Hitpael:'הִתְקַטֵּל'}[stem]]]}], examples:[{text:{Qal:'שָׁמַר',Niphal:'נִשְׁמַר',Piel:'דִּבֵּר',Pual:'כֻּבַּד',Hiphil:'הִמְלִיךְ',Hophal:'הָמְלַךְ',Hitpael:'הִתְהַלֵּךְ'}[stem], note:`sample ${stem} form`}], related:['hebrew-qal','hebrew-niphal','hebrew-piel','hebrew-hiphil'].filter(id=>id!==`hebrew-${stem.toLowerCase()}`) }))
  ];
  function topicLabel(id){ return topics.find(t => t.id === id)?.title || id; }
  function flattenTopic(topic){ return [topic.title, topic.category, topic.summary, ...(topic.body||[]), ...(topic.charts||[]).flatMap(c=>[c.label,...(c.columns||[]),...(c.rows||[]).flat()]), ...(topic.examples||[]).flatMap(e=>[e.text,e.note]), ...(topic.related||[]).map(topicLabel)].join(' ').toLowerCase(); }
  function searchReferenceTopics(query='', language='all'){
    const q = String(query).trim().toLowerCase();
    return topics.filter(t => (language === 'all' || t.language === language) && (!q || flattenTopic(t).includes(q)));
  }
  const api = { referenceTopics: topics, searchReferenceTopics, getReferenceTopic: id => topics.find(t => t.id === id), topicLabel };
  if(typeof module !== 'undefined' && module.exports) module.exports = api;
  root.PuritanReferenceLibrary = api;
})(typeof window !== 'undefined' ? window : globalThis);
