/* ---------- Grammar & Reference Library Data ---------- */
(function(root){
  const COLORS = { tense:'blue', voice:'green', mood:'purple', qal:'blue', niphal:'green', piel:'orange', pual:'amber', hiphil:'red', hophal:'gray', hitpael:'teal' };
  const ex = (word, reference, translation, note='') => ({ word, reference, translation, note });
  const chart = (label, columns, rows, options={}) => ({ label, columns, rows, ...options });
  const featureLinks = (...links) => links.map(([label, type, target]) => ({ label, type, target }));
  const greekVerbChart = chart('λύω present active indicative endings', ['Person','Singular','Plural','Recognition clue'], [['1st','λύω','λύομεν','ω / μεν'],['2nd','λύεις','λύετε','εις / τε'],['3rd','λύει','λύουσι(ν)','ει / ουσι']], { color:'tense', note:'Representative omega-verb forms; accents and movable nu may vary.' });
  const hebrewStemRows = [['Perfect','כָּתַב','completed/simple action'],['Imperfect','יִכְתֹּב','prefixed imperfect form'],['Imperative','כְּתֹב','command form'],['Infinitive Construct','כְּתֹב','verbal noun, often with לְ'],['Infinitive Absolute','כָּתוֹב','intensifying or verbal noun use'],['Participle','כֹּתֵב','verbal adjective/ongoing action']];
  const stemInfo = {
    Qal:['simple active/stative','קָטַל','basic lexical action'], Niphal:['passive/reflexive of Qal','נִקְטַל','often has נ or assimilated nun'], Piel:['intensive/factitive active','קִטֵּל','doubled middle radical'], Pual:['passive of Piel','קֻטַּל','u-class vowel with doubling'], Hiphil:['causative active','הִקְטִיל','prefixed הִ and causative sense'], Hophal:['passive of Hiphil','הָקְטַל','ho/ha class causative passive'], Hitpael:['reflexive/reciprocal','הִתְקַטֵּל','הת prefix plus doubling']
  };
  const stemRelationships = ['Qal gives the simple lexical baseline for many roots.','Niphal commonly presents the Qal idea as passive or reflexive.','Piel and Pual often form an active/passive pair with intensified, factitive, or result-focused force.','Hiphil and Hophal often form a causative active/passive pair.','Hitpael commonly adds reflexive or reciprocal involvement.'];
  const hebrewStemTopic = stem => ({ id:`hebrew-${stem.toLowerCase()}`, language:'hebrew', title:stem, category:'Verbal stems', color:stem.toLowerCase(), frequency: stem==='Qal' ? '≈ majority of Hebrew verbal forms' : stem==='Niphal' ? 'common major stem' : 'regular major stem; less frequent than Qal', summary:`${stem} is one of the major Biblical Hebrew verbal stems (binyanim).`, body:[stem==='Qal'?'Qal is the basic/light stem and often carries the simple lexical meaning of the verb.':`${stem} modifies the root idea in a conventional stem relationship; exact meaning depends on the root and context.`, ...stemRelationships], recognitionTips: stem==='Hiphil' ? ['Look for prefixed הִ in perfect and infinitive forms.','Expect causative meaning when the lexicon and context support it.','Characteristic i-class vowels often mark the stem.'] : [`Watch for the ${stemInfo[stem][1]} pattern.`, stemInfo[stem][2], 'Confirm the stem by both consonantal pattern and vowels.'], charts:[chart(`${stem} quick profile`, ['Stem','Typical value','Pattern','Recognition'], [[stem, stemInfo[stem][0], stemInfo[stem][1], stemInfo[stem][2]]], { color:stem.toLowerCase(), note:'Representative strong-verb pattern.' }), chart(`${stem} representative paradigm: כתב`, ['Form','Representative','Use'], hebrewStemRows.map(r=>[r[0], stem==='Qal'?r[1]:`${stemInfo[stem][1].replace(/[קטל]/g, m=>({ק:'כ',ט:'ת',ל:'ב'}[m]))}`, r[2]]), { color:stem.toLowerCase() })], examples:[ex(stem==='Hiphil'?'הִכְתִּיב':'כָּתַב', stem==='Qal'?'Jeremiah 36:2':'Reference example', stem==='Qal'?'he wrote / write':'representative stem form', `sample ${stem} form`)], paradigmTabs:hebrewTabs(stem), breadcrumbs:['Grammar','Paradigms',stem], stemRelationships:{ root:'כתב', stems:['Qal','Niphal','Piel','Pual','Hiphil','Hophal','Hitpael'], explanation:stemRelationships }, featureLinks:featureLinks(['See words with this feature','feature',stem],['See related vocabulary','vocabulary',stem],['See related topics','topics',`hebrew-${stem.toLowerCase()}`]), related:['hebrew-qal','hebrew-niphal','hebrew-piel','hebrew-pual','hebrew-hiphil','hebrew-hophal','hebrew-hitpael','hebrew-stem-markers'].filter(id=>id!==`hebrew-${stem.toLowerCase()}`) });

  const greekLyoTabs = [
    { id:'present', label:'Present', charts:[chart('Present Active Indicative', ['Person','Singular','Plural'], [['1st','λύω','λύομεν'],['2nd','λύεις','λύετε'],['3rd','λύει','λύουσι(ν)']]), chart('Present Middle/Passive', ['Person','Singular','Plural'], [['1st','λύομαι','λυόμεθα'],['2nd','λύῃ / λύει','λύεσθε'],['3rd','λύεται','λύονται']])]},
    { id:'imperfect', label:'Imperfect', charts:[chart('Imperfect Active Indicative', ['Person','Singular','Plural'], [['1st','ἔλυον','ἐλύομεν'],['2nd','ἔλυες','ἐλύετε'],['3rd','ἔλυε(ν)','ἔλυον']])]},
    { id:'future', label:'Future', charts:[chart('Future Active Indicative', ['Person','Singular','Plural'], [['1st','λύσω','λύσομεν'],['2nd','λύσεις','λύσετε'],['3rd','λύσει','λύσουσι(ν)']])]},
    { id:'aorist', label:'Aorist', charts:[chart('Aorist Active Indicative', ['Person','Singular','Plural'], [['1st','ἔλυσα','ἐλύσαμεν'],['2nd','ἔλυσας','ἐλύσατε'],['3rd','ἔλυσε(ν)','ἔλυσαν']]), chart('Aorist Passive', ['Person','Singular','Plural'], [['1st','ἐλύθην','ἐλύθημεν'],['2nd','ἐλύθης','ἐλύθητε'],['3rd','ἐλύθη','ἐλύθησαν']])]},
    { id:'perfect', label:'Perfect', charts:[chart('Perfect Active Indicative', ['Person','Singular','Plural'], [['1st','λέλυκα','λελύκαμεν'],['2nd','λέλυκας','λελύκατε'],['3rd','λέλυκε(ν)','λελύκασι(ν)']])]},
    { id:'imperative', label:'Imperative', charts:[chart('Imperative', ['Tense/Voice','2sg','3sg','2pl','3pl'], [['Present Active','λῦε','λυέτω','λύετε','λυόντων'],['Aorist Active','λῦσον','λυσάτω','λύσατε','λυσάντων'],['Present Mid/Pass','λύου','λυέσθω','λύεσθε','λυέσθων']])]},
    { id:'infinitive', label:'Infinitive', charts:[chart('Infinitive', ['Tense/Voice','Form'], [['Present Active','λύειν'],['Aorist Active','λῦσαι'],['Perfect Active','λελυκέναι'],['Present Mid/Pass','λύεσθαι'],['Aorist Passive','λυθῆναι']])]},
    { id:'participle', label:'Participle', charts:[chart('Participle (nominative singular)', ['Tense/Voice','Masc','Fem','Neut'], [['Present Active','λύων','λύουσα','λῦον'],['Aorist Active','λύσας','λύσασα','λῦσαν'],['Perfect Active','λελυκώς','λελυκυῖα','λελυκός'],['Present Mid/Pass','λυόμενος','λυομένη','λυόμενον'],['Aorist Passive','λυθείς','λυθεῖσα','λυθέν']])]},
    { id:'principal-parts', label:'Principal Parts', charts:[chart('Principal parts', ['Part','Form'], [['Present','λύω'],['Future active','λύσω'],['Aorist active','ἔλυσα'],['Perfect active','λέλυκα'],['Perfect middle/passive','λέλυμαι'],['Aorist passive','ἐλύθην']])]}
  ];
  const hebPersons = ['3ms','3fs','2ms','2fs','1cs','3mp','3fp','2mp','2fp','1cp'];
  const hebrewForms = {
    Qal:[['כָּתַב','כָּתְבָה','כָּתַבְתָּ','כָּתַבְתְּ','כָּתַבְתִּי','כָּתְבוּ','כָּתְבוּ','כְּתַבְתֶּם','כְּתַבְתֶּן','כָּתַבְנוּ'],['יִכְתֹּב','תִּכְתֹּב','תִּכְתֹּב','תִּכְתְּבִי','אֶכְתֹּב','יִכְתְּבוּ','תִּכְתֹּבְנָה','תִּכְתְּבוּ','תִּכְתֹּבְנָה','נִכְתֹּב']],
    Niphal:[['נִכְתַּב','נִכְתְּבָה','נִכְתַּבְתָּ','נִכְתַּבְתְּ','נִכְתַּבְתִּי','נִכְתְּבוּ','נִכְתְּבוּ','נִכְתַּבְתֶּם','נִכְתַּבְתֶּן','נִכְתַּבְנוּ'],['יִכָּתֵב','תִּכָּתֵב','תִּכָּתֵב','תִּכָּתְבִי','אִכָּתֵב','יִכָּתְבוּ','תִּכָּתַבְנָה','תִּכָּתְבוּ','תִּכָּתַבְנָה','נִכָּתֵב']],
    Piel:[['כִּתֵּב','כִּתְּבָה','כִּתַּבְתָּ','כִּתַּבְתְּ','כִּתַּבְתִּי','כִּתְּבוּ','כִּתְּבוּ','כִּתַּבְתֶּם','כִּתַּבְתֶּן','כִּתַּבְנוּ'],['יְכַתֵּב','תְּכַתֵּב','תְּכַתֵּב','תְּכַתְּבִי','אֲכַתֵּב','יְכַתְּבוּ','תְּכַתֵּבְנָה','תְּכַתְּבוּ','תְּכַתֵּבְנָה','נְכַתֵּב']],
  };
  hebrewForms.Pual=hebrewForms.Piel; hebrewForms.Hiphil=hebrewForms.Piel; hebrewForms.Hophal=hebrewForms.Niphal; hebrewForms.Hitpael=hebrewForms.Piel;
  const hebrewTabs = stem => [{id:'perfect',label:'Perfect',charts:[chart(`${stem} Perfect: כתב`, ['Person',...hebPersons], [['Form',...hebrewForms[stem][0]]])]}, {id:'imperfect',label:'Imperfect',charts:[chart(`${stem} Imperfect: כתב`, ['Person',...hebPersons], [['Form',...hebrewForms[stem][1]]])]}, {id:'imperative',label:'Imperative',charts:[chart(`${stem} Imperative`, ['2ms','2fs','2mp','2fp'], [['Form','כְּתֹב','כִּתְבִי','כִּתְבוּ','כְּתֹבְנָה']])]}, {id:'infinitives',label:'Infinitives',charts:[chart(`${stem} Infinitives`, ['Type','Form'], [['Construct', stem==='Hiphil'?'הַכְתִּיב':'כְּתֹב'],['Absolute', stem==='Hiphil'?'הַכְתֵּב':'כָּתוֹב']])]}, {id:'participles',label:'Participles',charts:[chart(`${stem} Participles`, ['Gender/Number','Form'], [['ms','כֹּתֵב'],['fs','כֹּתֶבֶת'],['mp','כֹּתְבִים'],['fp','כֹּתְבוֹת']])]}, {id:'recognition',label:'Recognition',charts:[chart(`${stem} recognition`, ['Clue','Tip'], [[stemInfo[stem][1], stemInfo[stem][2]],['Root','כתב']])]}];
  const decoderEntries = {
    'V-PAI-3S': { breakdown:['Verb','Present Active Indicative','3rd singular'], tips:['Look for present stem plus active ending.'], examples:['λύει'], related:['greek-lyo-paradigm','greek-verb-endings'] },
    'V-AAI-1P': { breakdown:['Verb','Aorist Active Indicative','1st plural'], tips:['Augment plus σα often marks first aorist.'], examples:['ἐλύσαμεν'], related:['greek-lyo-paradigm','greek-common-parsing-clues'] },
    'N-GSM': { breakdown:['Noun','Genitive Singular Masculine'], tips:['ου is a common second-declension genitive clue.'], examples:['λόγου'], related:['greek-logos-paradigm','greek-noun-endings'] },
    'A-NSF': { breakdown:['Adjective','Nominative Singular Feminine'], tips:['Adjectives agree with nouns they modify.'], examples:['καλή'], related:['greek-kalos-paradigm'] },
    'QAL PERFECT 3MS': { breakdown:['Qal stem','Perfect conjugation','3ms'], tips:['Basic stem; perfect 3ms is often the lexical baseline.'], examples:['כָּתַב'], related:['hebrew-qal'] },
    'HIPHIL IMPERFECT 2MP': { breakdown:['Hiphil stem','Imperfect conjugation','2mp'], tips:['Look for causative ה/י pattern and 2mp ending וּ.'], examples:['תַּכְתִּיבוּ'], related:['hebrew-hiphil','hebrew-prefixes'] }
  };

  const topics = [
    { id:'grammar-parsing-decoder', language:'greek', title:'Parsing Decoder', category:'Tools', summary:'Lookup helper that opens the interactive parsing decoder for Greek and Hebrew parsing codes.', body:['Use this entry to open the existing Parsing Decoder UI from Grammar search results.'], recognitionTips:['Search for parsing decoder when you need to interpret a parsing code.'], charts:[], examples:[ex('V-AAI-1P','Parsing code','Aorist active indicative, first plural'), ex('Hiphil Imperfect 2mp','Parsing code','Hiphil imperfect, second masculine plural')], related:['greek-common-parsing-clues','greek-verb-endings','hebrew-stem-markers'] },
    { id:'greek-articles', language:'greek', title:'Articles', category:'Nominals', summary:'The Greek article marks case, number, and gender and often identifies a noun as definite or previously known.', body:['Articles are parsing anchors: parse the article and you often know the nearby noun pattern.'], recognitionTips:['ὁ/οἱ often point to masculine nominative forms.','τοῦ/τῶν are strong genitive clues.','τό can be nominative or accusative neuter singular.'], charts:[chart('Greek article chart', ['Case','Masculine','Feminine','Neuter'], [['Nom sg','ὁ','ἡ','τό'],['Gen sg','τοῦ','τῆς','τοῦ'],['Dat sg','τῷ','τῇ','τῷ'],['Acc sg','τόν','τήν','τό'],['Nom pl','οἱ','αἱ','τά'],['Gen pl','τῶν','τῶν','τῶν'],['Dat pl','τοῖς','ταῖς','τοῖς'],['Acc pl','τούς','τάς','τά']], { color:'blue', note:'The article agrees with its noun.' })], examples:[ex('ὁ λόγος','John 1:1','the Word'), ex('τὰ ἔργα','James 2:18','the works')], related:['greek-logos-paradigm','greek-noun-endings','greek-pronouns'] },
    { id:'greek-pronouns', language:'greek', title:'Pronouns', category:'Nominals', summary:'Pronouns replace or point to nouns and are parsed for case, number, gender, and sometimes person.', body:['Pronouns must be read in context because their antecedent may be nearby or implied.'], recognitionTips:['αὐτός may function as he/she/it, self, or same.','Relative pronouns often introduce dependent clauses.'], charts:[chart('Personal pronouns', ['Person','Nominative','Genitive','Accusative'], [['1 sg','ἐγώ','μου / ἐμοῦ','με / ἐμέ'],['2 sg','σύ','σου / σοῦ','σε / σέ'],['3 masc sg','αὐτός','αὐτοῦ','αὐτόν']])], examples:[ex('αὐτός','Matthew 1:21','he'), ex('ἐγώ','John 8:32','I')], related:['greek-articles','greek-noun-endings'] },
    { id:'greek-verb-overview', language:'greek', title:'Verb overview', category:'Verbs', summary:'Greek verbs communicate action or state through tense-form, voice, mood, person, and number.', body:['Start with tense-form, voice, and mood, then confirm person and number from endings.'], recognitionTips:['Personal endings carry person and number.','Augment often points to past indicative forms.','Connecting vowels often appear before endings.'], charts:[chart('Main parsing categories', ['Category','Question'], [['Tense-form','What viewpoint/time?'],['Voice','How is the subject related?'],['Mood','How is the action presented?']], { color:'tense' }), greekVerbChart], examples:[ex('λύω','John 8:32','I release / loose'), ex('λέγω','Matthew 5:37','I say')], related:['greek-tense-explanations','greek-voice-explanations','greek-mood-explanations','greek-lyo-paradigm','greek-verb-endings'] },
    { id:'greek-tense-explanations', language:'greek', title:'Tense explanations', category:'Verbs', color:'tense', frequency:'Present and aorist are very common tense-forms.', summary:'Greek tense-forms combine aspect with time most clearly in the indicative mood.', body:['Present/imperfect usually present imperfective aspect; aorist usually presents perfective aspect; perfect emphasizes a resulting state.'], recognitionTips:['Present often uses the present stem plus primary endings.','Aorist often has augment and σα or second-aorist stem changes.'], charts:[chart('Greek tense-form overview', ['Tense-form','Typical force'], [['Present','ongoing/imperfective'],['Imperfect','past ongoing'],['Aorist','summary/perfective'],['Perfect','completed with result'],['Future','future-oriented']], { color:'tense' })], examples:[ex('λύω','John 8:32','I release'), ex('λέγω','Matthew 5:37','I say')], related:['greek-verb-overview','greek-voice-explanations','greek-mood-explanations'] },
    { id:'greek-voice-explanations', language:'greek', title:'Voice explanations', category:'Verbs', color:'voice', summary:'Voice describes the subject’s relationship to the action.', body:['Active presents the subject acting; passive presents the subject acted upon; middle highlights subject involvement.'], recognitionTips:['μαι/σαι/ται endings often mark middle/passive forms.','θη often points to aorist passive.'], charts:[chart('Voice overview', ['Voice','Basic idea'], [['Active','subject acts'],['Middle','subject participates'],['Passive','subject receives action']], { color:'voice' })], examples:[ex('λύεται','Mark 7:35','is loosed/opened'), ex('ἐλήμφθην','Representative','I was taken')], related:['greek-verb-overview','greek-tense-explanations','greek-mood-explanations'] },
    { id:'greek-mood-explanations', language:'greek', title:'Mood explanations', category:'Verbs', color:'mood', frequency:'Indicative mood ≈ most finite verbs.', summary:'Mood presents action as assertion, possibility, command, verbal idea, or adjectival verbal form.', body:['Indicative states or asks; subjunctive often presents potential/purpose; imperative commands.'], recognitionTips:['ωμεν/ητε can mark subjunctive endings.','Imperatives often lack an explicit subject.'], charts:[chart('Mood overview', ['Mood','Common use'], [['Indicative','statement/question'],['Subjunctive','potential/purpose'],['Imperative','command'],['Infinitive','verbal noun'],['Participle','verbal adjective']], { color:'mood' })], examples:[ex('λέγει','Matthew 5:37','he says'), ex('πιστεύωμεν','Representative','let us believe')], related:['greek-verb-overview','greek-tense-explanations','greek-voice-explanations'] },
    { id:'greek-noun-endings', language:'greek', title:'Noun endings cheat sheet', category:'Cheat sheets', summary:'Common noun endings help students recognize case and number quickly.', body:['Use endings as clues, then confirm with article, adjective agreement, and context.'], recognitionTips:['ος → often nominative masculine singular.','ου → often genitive singular.','οι → often nominative masculine plural.','ον → often accusative masculine singular or neuter nominative/accusative singular.'], charts:[chart('Common noun ending clues', ['Ending','Likely parse','Example'], [['ος','nominative masculine singular','λόγος'],['ου','genitive singular','λόγου'],['ῳ','dative singular','λόγῳ'],['ον','accusative masculine singular','λόγον'],['οι','nominative masculine plural','λόγοι']])], examples:[ex('λόγος','John 1:1','word'), ex('λόγου','John 1:14','of a word / word')], related:['greek-logos-paradigm','greek-articles'] },
    { id:'greek-verb-endings', language:'greek', title:'Verb endings cheat sheet', category:'Cheat sheets', summary:'Common verb endings give quick person, number, voice, and mood clues.', body:['Endings are pattern-recognition aids, not a substitute for context.'], recognitionTips:['ω endings often mark first singular active.','ει endings often mark third singular active.','ουσι endings often mark third plural active.'], charts:[greekVerbChart], examples:[ex('λύω','John 8:32','I release'), ex('λέγω','Matthew 5:37','I say')], related:['greek-lyo-paradigm','greek-verb-overview'] },
    { id:'greek-common-parsing-clues', language:'greek', title:'Common parsing clues', category:'Cheat sheets', summary:'A compact checklist for recognizing common Greek forms.', body:['Look for articles, augments, endings, stem changes, and prepositional contexts.'], recognitionTips:['Augment ε often points to past indicative.','θη often points to passive.','σ before endings may signal future or first aorist.'], charts:[chart('Parsing clue checklist', ['Clue','Often indicates'], [['ε augment','past indicative'],['θη','aorist passive'],['σ + ending','future or first aorist'],['μαι/σαι/ται','middle/passive']])], examples:[ex('ἐλήμφθην','Representative','I was taken')], related:['greek-tense-explanations','greek-voice-explanations'] },
    { id:'greek-lyo-paradigm', language:'greek', title:'λύω paradigm', category:'Paradigms', summary:'Representative Greek omega-verb paradigm with principal parts.', body:['This is an educational reference page for recognizing regular omega-verb patterns.'], principalParts:['λύω','λύσω','ἔλυσα','λέλυκα','λέλυμαι','ἐλύθην'], paradigmTabs:greekLyoTabs, breadcrumbs:['Grammar','Paradigms','λύω'], recognitionTips:['Present active indicative uses ω, εις, ει, ομεν, ετε, ουσι.','Middle/passive forms often use μαι endings.'], charts:[greekVerbChart, chart('Principal parts', ['Part','Form'], [['Present','λύω'],['Future active','λύσω'],['Aorist active','ἔλυσα'],['Perfect active','λέλυκα'],['Perfect middle/passive','λέλυμαι'],['Aorist passive','ἐλύθην']])], examples:[ex('λύω','John 8:32','I release / loose')], related:['greek-verb-endings','greek-verb-overview'] },
    { id:'greek-logos-paradigm', language:'greek', title:'λόγος paradigm', category:'Paradigms', summary:'Representative second-declension masculine noun paradigm.', body:['λόγος illustrates many common second-declension noun endings.'], recognitionTips:['ος is a common nominative singular ending.','ου is a common genitive singular ending.'], breadcrumbs:['Grammar','Paradigms','λόγος'], charts:[chart('λόγος noun paradigm', ['Case','Singular','Plural'], [['Nom','λόγος','λόγοι'],['Gen','λόγου','λόγων'],['Dat','λόγῳ','λόγοις'],['Acc','λόγον','λόγους']])], examples:[ex('λόγος','John 1:1','word')], related:['greek-noun-endings','greek-articles'] },
    { id:'greek-kalos-paradigm', language:'greek', title:'καλός paradigm', category:'Paradigms', summary:'Representative 2-1-2 adjective paradigm.', body:['καλός illustrates adjective agreement across masculine, feminine, and neuter forms.'], recognitionTips:['Adjectives agree with nouns in case, number, and gender.','Neuter nominative and accusative forms often match.'], breadcrumbs:['Grammar','Paradigms','καλός'], charts:[chart('καλός adjective endings', ['Gender','Nom sg','Acc sg','Nom pl','Acc pl'], [['Masc','καλός','καλόν','καλοί','καλούς'],['Fem','καλή','καλήν','καλαί','καλάς'],['Neut','καλόν','καλόν','καλά','καλά']])], examples:[ex('καλός','John 10:11','good')], related:['greek-articles','greek-noun-endings'] },
    { id:'hebrew-pronouns', language:'hebrew', title:'Pronouns', category:'Nominals', summary:'Hebrew pronouns mark person, gender, and number and may stand alone or attach as suffixes.', body:['Independent pronouns often supply emphasis or serve as subjects in verbless clauses.'], recognitionTips:['הוּא is 3ms; הִיא is 3fs.','Suffixes attach to nouns, prepositions, and verbs.'], charts:[chart('Independent pronouns', ['Person','Singular','Plural'], [['1 common','אֲנִי / אָנֹכִי','אֲנַחְנוּ'],['2 masculine','אַתָּה','אַתֶּם'],['2 feminine','אַתְּ','אַתֶּן'],['3 masculine','הוּא','הֵם'],['3 feminine','הִיא','הֵנָּה']])], examples:[ex('אֲנִי','Exodus 20:2','I'), ex('הוּא','Genesis 2:11','it / he')], related:['hebrew-suffixes','hebrew-noun-basics'] },
    { id:'hebrew-noun-basics', language:'hebrew', title:'Noun patterns / noun basics', category:'Nominals', summary:'Hebrew nouns have gender, number, and state; construct chains are central to noun syntax.', body:['The construct state links one noun closely to a following noun, often translated with “of.”'], recognitionTips:['־ִים often marks masculine plural.','־וֹת often marks feminine plural.','Construct nouns are bound closely to the following noun.'], charts:[chart('Noun pattern clues', ['Feature','Common marker'], [['Masculine plural','־ִים'],['Feminine singular','־ָה / ־ת'],['Feminine plural','־וֹת'],['Construct','bound form before another noun']])], examples:[ex('דְּבַר יְהוָה','Jeremiah 1:2','word of YHWH'), ex('סוּסִים','Representative','horses')], related:['hebrew-pronouns','hebrew-suffixes'] },
    { id:'hebrew-prefixes', language:'hebrew', title:'Prefixes cheat sheet', category:'Cheat sheets', summary:'Common Hebrew prefixes help identify conjunctions, prepositions, articles, and verbal forms.', body:['Prefixes stack, so identify each element from left to right.'], recognitionTips:['וַי → wayyiqtol narrative form.','הִ → often Hiphil in the right verbal context.','לְ, בְּ, כְּ attach directly to words.'], charts:[chart('Common prefixes', ['Prefix','Recognition'], [['וַי','wayyiqtol'],['הִ','Hiphil clue'],['נִ','Niphal clue'],['הַ','article or interrogative depending context'],['לְ','to/for or infinitive marker']])], examples:[ex('וַיֹּאמֶר','Genesis 1:3','and he said')], related:['hebrew-wayyiqtol','hebrew-stem-markers'] },
    { id:'hebrew-suffixes', language:'hebrew', title:'Suffixes cheat sheet', category:'Cheat sheets', summary:'Hebrew suffixes mark pronominal relationships and some verbal parsing information.', body:['Suffixes can show possession, objects, or verbal person/number/gender.'], recognitionTips:['וֹ often marks his/its on nouns.','תִּי often marks first common singular perfect.'], charts:[chart('Common suffix clues', ['Suffix','Often indicates'], [['וֹ','his/its'],['ךָ','your masculine singular'],['תִּי','I, perfect'],['וּ','they or plural marker depending form']])], examples:[ex('סוּסוֹ','Representative','his horse')], related:['hebrew-pronouns'] },
    { id:'hebrew-wayyiqtol', language:'hebrew', title:'Wayyiqtol recognition', category:'Cheat sheets', summary:'Wayyiqtol is a common Biblical Hebrew narrative sequence form.', body:['Wayyiqtol often advances narrative with “and he/they ...” in past-time contexts.'], recognitionTips:['וַי is the key visual clue.','Look for doubled prefix consonant when spelling allows.','Translate according to narrative context, not mechanically.'], charts:[chart('Wayyiqtol clues', ['Clue','Example'], [['וַי + imperfect','וַיֹּאמֶר'],['Narrative sequence','and he said / then he said']])], examples:[ex('וַיֹּאמֶר','Genesis 1:3','and he said')], related:['hebrew-prefixes','hebrew-qal'] },
    { id:'hebrew-stem-markers', language:'hebrew', title:'Stem markers cheat sheet', category:'Cheat sheets', summary:'Quick recognition markers for the major Hebrew stems.', body:['Use consonants, vowels, and meaning together to identify a stem.'], recognitionTips:['נִ often points to Niphal.','Doubled middle radical often points to Piel/Pual/Hitpael.','הִ often points to Hiphil.'], charts:[chart('Stem marker overview', ['Stem','Marker','Typical relationship'], Object.entries(stemInfo).map(([s,v])=>[s,v[1],v[0]]))], examples:[ex('הִכְתִּיב','Representative','he caused to write')], related:['hebrew-qal','hebrew-niphal','hebrew-piel','hebrew-hiphil'] },
    ...['Qal','Niphal','Piel','Pual','Hiphil','Hophal','Hitpael'].map(hebrewStemTopic),
    { id:'hebrew-katav-stem-relationships', language:'hebrew', title:'כתב stem relationships', category:'Paradigms', summary:'A single-root overview showing how כתב relates across major Hebrew stems.', body:['This page compares stem relationships without generating forms dynamically.'], recognitionTips:['Start with the root consonants כ־ת־ב.','Then identify stem markers around the root.'], charts:[chart('כתב across stems', ['Stem','Relationship','Representative pattern'], Object.entries(stemInfo).map(([s,v])=>[s,v[0],v[1]]))], examples:[ex('אָמַר','Genesis 1:3','he said'), ex('כתב','Jeremiah 36:2','write')], stemRelationships:{ root:'כתב', stems:['Qal','Niphal','Piel','Pual','Hiphil','Hophal','Hitpael'], explanation:stemRelationships }, related:['hebrew-qal','hebrew-niphal','hebrew-piel','hebrew-pual','hebrew-hiphil','hebrew-hophal','hebrew-hitpael'] }
  ];
  function topicLabel(id){ return topics.find(t => t.id === id)?.title || id; }
  function cellText(cell){ return typeof cell === 'object' && cell !== null ? Object.values(cell).join(' ') : String(cell ?? ''); }
  function normalizeSearchText(value){ return String(value ?? '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase(); }
  function flattenTopic(topic){ return [topic.id, topic.title, topic.category, topic.summary, topic.frequency, ...(topic.body||[]), ...(topic.recognitionTips||[]), ...(topic.principalParts||[]), ...(topic.paradigmTabs||[]).flatMap(tab=>[tab.label,...(tab.charts||[]).flatMap(c=>[c.label,c.note,...(c.columns||[]),...(c.rows||[]).flat().map(cellText)])]), ...(topic.charts||[]).flatMap(c=>[c.heading,c.label,c.note,c.color,...(c.columns||[]),...(c.rows||[]).flat().map(cellText)]), ...(topic.examples||[]).flatMap(e=>[e.word,e.reference,e.translation,e.note,e.text]), ...(topic.related||[]).map(topicLabel), ...(topic.featureLinks||[]).flatMap(l=>[l.label,l.type,l.target]), topic.stemRelationships?.root, ...(topic.stemRelationships?.stems||[]), ...(topic.stemRelationships?.explanation||[])].join(' '); }
  function searchReferenceTopics(query='', language='all'){
    const q = normalizeSearchText(String(query).trim());
    return topics.filter(t => (language === 'all' || t.language === language) && (!q || normalizeSearchText(flattenTopic(t)).includes(q)));
  }
  function decodeParsing(input){ const key=String(input||'').trim().toUpperCase().replace(/\s+/g,' '); return decoderEntries[key] || null; }
  const api = { referenceTopics: topics, searchReferenceTopics, getReferenceTopic: id => topics.find(t => t.id === id), topicLabel, referenceColors: COLORS, decodeParsing, decoderEntries };
  if(typeof module !== 'undefined' && module.exports) module.exports = api;
  root.PuritanReferenceLibrary = api;
})(typeof window !== 'undefined' ? window : globalThis);
