/* ---------- Grammar & Reference Library Data ---------- */
(function(root){
  const COLORS = { tense:'blue', voice:'green', mood:'purple', qal:'blue', niphal:'green', piel:'orange', pual:'amber', hiphil:'red', hophal:'gray', hitpael:'teal' };
  const ex = (word, reference, translation, note='') => ({ word, reference, translation, note });
  const chart = (label, columns, rows, options={}) => ({ label, columns, rows, ...options });
  const featureLinks = (...links) => links.map(([label, type, target]) => ({ label, type, target }));
  const greekVerbChart = chart('λύω present active indicative endings', ['Person','Singular','Plural','Recognition clue'], [['1st','λύω','λύομεν','ω / μεν'],['2nd','λύεις','λύετε','εις / τε'],['3rd','λύει','λύουσι(ν)','ει / ουσι']], { color:'tense', note:'Representative omega-verb forms; accents and movable nu may vary.' });
  const hebrewStemRows = [['Perfect','כָּתַב','completed/simple action'],['Imperfect','יִכְתֹּב','prefixed imperfect form'],['Imperative','כְּתֹב','command form'],['Infinitive Construct','כְּתֹב','verbal noun, often with לְ'],['Infinitive Absolute','כָּתוֹב','intensifying or verbal noun use'],['Participle','כֹּתֵב','verbal adjective/ongoing action']];
  const stemInfo = {
    Qal:['simple active/stative','קָטַל','basic lexical action'], Niphal:['passive/reflexive of Qal','נִקְטַל','often has נ or assimilated nun'], Piel:['intensive/factitive active','קִטֵּל','doubled middle radical'], Pual:['passive of Piel','קֻטַּל','u-class vowel with doubling'], Hiphil:['causative active','הִקְטִיל','prefixed הִ and causative sense'], Hophal:['passive of Hiphil','הָקְטַל','ho/ha class causative passive'], Hitpael:['reflexive/reciprocal','הִתְקַטֵּל','הת prefix plus doubling']
  };
  const stemRelationships = ['Qal gives the simple lexical baseline for many roots.','Niphal commonly presents the Qal idea as passive or reflexive.','Piel and Pual often form an active/passive pair with intensified, factitive, or result-focused force.','Hiphil and Hophal often form a causative active/passive pair.','Hitpael commonly adds reflexive or reciprocal involvement.'];
  const hebrewStemTopic = stem => ({ id:`hebrew-${stem.toLowerCase()}`, language:'hebrew', title:stem, category:`${stem} Paradigms`, color:stem.toLowerCase(), frequency: stem==='Qal' ? '≈ majority of Hebrew verbal forms' : stem==='Niphal' ? 'common major stem' : 'regular major stem; less frequent than Qal', summary:`${stem} is one of the major Biblical Hebrew verbal stems (binyanim).`, body:[stem==='Qal'?'Qal is the basic/light stem and often carries the simple lexical meaning of the verb.':`${stem} modifies the root idea in a conventional stem relationship; exact meaning depends on the root and context.`, ...stemRelationships], recognitionTips: stem==='Hiphil' ? ['Look for prefixed הִ in perfect and infinitive forms.','Expect causative meaning when the lexicon and context support it.','Characteristic i-class vowels often mark the stem.'] : [`Watch for the ${stemInfo[stem][1]} pattern.`, stemInfo[stem][2], 'Confirm the stem by both consonantal pattern and vowels.'], charts:[chart(`${stem} quick profile`, ['Stem','Typical value','Pattern','Recognition'], [[stem, stemInfo[stem][0], stemInfo[stem][1], stemInfo[stem][2]]], { color:stem.toLowerCase(), note:'Representative strong-verb pattern.' }), chart(`${stem} representative paradigm: כתב`, ['Form','Representative','Use'], hebrewStemRows.map(r=>[r[0], stem==='Qal'?r[1]:`${stemInfo[stem][1].replace(/[קטל]/g, m=>({ק:'כ',ט:'ת',ל:'ב'}[m]))}`, r[2]]), { color:stem.toLowerCase() })], examples:[ex(stem==='Hiphil'?'הִכְתִּיב':'כָּתַב', stem==='Qal'?'Jeremiah 36:2':'Reference example', stem==='Qal'?'he wrote / write':'representative stem form', `sample ${stem} form`)], paradigmTabs:hebrewTabs(stem), breadcrumbs:['Grammar','Hebrew',`${stem} Paradigms`], stemRelationships:{ root:'כתב', stems:['Qal','Niphal','Piel','Pual','Hiphil','Hophal','Hitpael'], explanation:stemRelationships }, featureLinks:featureLinks(['See words with this feature','feature',stem],['See related vocabulary','vocabulary',stem],['See related topics','topics',`hebrew-${stem.toLowerCase()}`]), related:['hebrew-qal','hebrew-niphal','hebrew-piel','hebrew-pual','hebrew-hiphil','hebrew-hophal','hebrew-hitpael','hebrew-stem-markers'].filter(id=>id!==`hebrew-${stem.toLowerCase()}`) });

  const six = rows => rows;
  const greekFinite = (label, sg, pl) => chart(label, ['Person','Singular','Plural'], [['1st',sg[0],pl[0]],['2nd',sg[1],pl[1]],['3rd',sg[2],pl[2]]]);
  const greekImperative = (label, forms) => chart(label, ['Person','Singular','Plural'], [['2nd',forms[0],forms[2]],['3rd',forms[1],forms[3]]]);
  const greekInfinitive = (label, form) => chart(label, ['Form'], [[form]]);
  const greekParticiple = (label, m, f, n) => chart(label, ['Case','Masculine','Feminine','Neuter'], [['Nom sg',m,f,n],['Gen sg',m.replace(/ων$|ος$/,'οντος'),f.replace(/α$|η$/,'ης'),n.replace(/ον$/,'οντος')],['Nom pl',m.replace(/ων$|ος$/,'οντες'),f.replace(/α$|η$/,'αι'),n.replace(/ον$/,'οντα')]]);
  const greekLyoTabs = [
    { id:'present', label:'Present', charts:[
      greekFinite('Present Active Indicative',['λύω','λύεις','λύει'],['λύομεν','λύετε','λύουσι(ν)']),
      greekFinite('Present Middle/Passive Indicative',['λύομαι','λύῃ / λύει','λύεται'],['λυόμεθα','λύεσθε','λύονται']),
      greekFinite('Present Active Subjunctive',['λύω','λύῃς','λύῃ'],['λύωμεν','λύητε','λύωσι(ν)']),
      greekFinite('Present Middle/Passive Subjunctive',['λύωμαι','λύῃ','λύηται'],['λυώμεθα','λύησθε','λύωνται']),
      greekImperative('Present Active Imperative',['λῦε','λυέτω','λύετε','λυόντων']),
      greekImperative('Present Middle/Passive Imperative',['λύου','λυέσθω','λύεσθε','λυέσθων']),
      greekInfinitive('Present Active Infinitive','λύειν'), greekInfinitive('Present Middle/Passive Infinitive','λύεσθαι'),
      greekParticiple('Present Active Participle','λύων','λύουσα','λῦον'), greekParticiple('Present Middle/Passive Participle','λυόμενος','λυομένη','λυόμενον') ]},
    { id:'imperfect', label:'Imperfect', charts:[greekFinite('Imperfect Active Indicative',['ἔλυον','ἔλυες','ἔλυε(ν)'],['ἐλύομεν','ἐλύετε','ἔλυον']), greekFinite('Imperfect Middle/Passive Indicative',['ἐλυόμην','ἐλύου','ἐλύετο'],['ἐλυόμεθα','ἐλύεσθε','ἐλύοντο'])]},
    { id:'future', label:'Future', charts:[greekFinite('Future Active Indicative',['λύσω','λύσεις','λύσει'],['λύσομεν','λύσετε','λύσουσι(ν)']), greekFinite('Future Middle Indicative',['λύσομαι','λύσῃ','λύσεται'],['λυσόμεθα','λύσεσθε','λύσονται']), greekFinite('Future Passive Indicative',['λυθήσομαι','λυθήσῃ','λυθήσεται'],['λυθησόμεθα','λυθήσεσθε','λυθήσονται'])]},
    { id:'aorist', label:'Aorist', charts:[
      greekFinite('Aorist Active Indicative',['ἔλυσα','ἔλυσας','ἔλυσε(ν)'],['ἐλύσαμεν','ἐλύσατε','ἔλυσαν']), greekFinite('Aorist Middle Indicative',['ἐλυσάμην','ἐλύσω','ἐλύσατο'],['ἐλυσάμεθα','ἐλύσασθε','ἐλύσαντο']), greekFinite('Aorist Passive Indicative',['ἐλύθην','ἐλύθης','ἐλύθη'],['ἐλύθημεν','ἐλύθητε','ἐλύθησαν']),
      greekFinite('Aorist Active Subjunctive',['λύσω','λύσῃς','λύσῃ'],['λύσωμεν','λύσητε','λύσωσι(ν)']), greekFinite('Aorist Middle Subjunctive',['λύσωμαι','λύσῃ','λύσηται'],['λυσώμεθα','λύσησθε','λύσωνται']), greekFinite('Aorist Passive Subjunctive',['λυθῶ','λυθῇς','λυθῇ'],['λυθῶμεν','λυθῆτε','λυθῶσι(ν)']),
      greekImperative('Aorist Active Imperative',['λῦσον','λυσάτω','λύσατε','λυσάντων']), greekImperative('Aorist Middle Imperative',['λῦσαι','λυσάσθω','λύσασθε','λυσάσθων']), greekImperative('Aorist Passive Imperative',['λύθητι','λυθήτω','λύθητε','λυθέντων']),
      greekInfinitive('Aorist Active Infinitive','λῦσαι'), greekInfinitive('Aorist Middle Infinitive','λύσασθαι'), greekInfinitive('Aorist Passive Infinitive','λυθῆναι'),
      greekParticiple('Aorist Active Participle','λύσας','λύσασα','λῦσαν'), greekParticiple('Aorist Middle Participle','λυσάμενος','λυσαμένη','λυσάμενον'), greekParticiple('Aorist Passive Participle','λυθείς','λυθεῖσα','λυθέν') ]},
    { id:'perfect', label:'Perfect', charts:[greekFinite('Perfect Active Indicative',['λέλυκα','λέλυκας','λέλυκε(ν)'],['λελύκαμεν','λελύκατε','λελύκασι(ν)']), greekFinite('Perfect Middle/Passive Indicative',['λέλυμαι','λέλυσαι','λέλυται'],['λελύμεθα','λέλυσθε','λέλυνται']), greekInfinitive('Perfect Active Infinitive','λελυκέναι'), greekInfinitive('Perfect Middle/Passive Infinitive','λελύσθαι'), greekParticiple('Perfect Active Participle','λελυκώς','λελυκυῖα','λελυκός'), greekParticiple('Perfect Middle/Passive Participle','λελυμένος','λελυμένη','λελυμένον')]},
    { id:'pluperfect', label:'Pluperfect', charts:[greekFinite('Pluperfect Active Indicative',['ἐλελύκειν','ἐλελύκεις','ἐλελύκει'],['ἐλελύκεμεν','ἐλελύκετε','ἐλελύκεσαν']), greekFinite('Pluperfect Middle/Passive Indicative',['ἐλελύμην','ἐλέλυσο','ἐλέλυτο'],['ἐλελύμεθα','ἐλέλυσθε','ἐλέλυντο'])]},
    { id:'non-finite', label:'Non-finite', charts:[chart('Infinitive quick index',['Tense/Voice','Form'],[['Present Active','λύειν'],['Present Middle/Passive','λύεσθαι'],['Aorist Active','λῦσαι'],['Aorist Middle','λύσασθαι'],['Aorist Passive','λυθῆναι'],['Perfect Active','λελυκέναι'],['Perfect Middle/Passive','λελύσθαι']]), chart('Participle quick index',['Tense/Voice','Masc nom sg','Fem nom sg','Neut nom sg'],[['Present Active','λύων','λύουσα','λῦον'],['Present Middle/Passive','λυόμενος','λυομένη','λυόμενον'],['Aorist Active','λύσας','λύσασα','λῦσαν'],['Aorist Middle','λυσάμενος','λυσαμένη','λυσάμενον'],['Aorist Passive','λυθείς','λυθεῖσα','λυθέν'],['Perfect Active','λελυκώς','λελυκυῖα','λελυκός'],['Perfect Middle/Passive','λελυμένος','λελυμένη','λελυμένον']])]},
    { id:'principal-parts', label:'Principal Parts', charts:[chart('Principal parts', ['Part','Form'], [['Present','λύω'],['Future active','λύσω'],['Aorist active','ἔλυσα'],['Perfect active','λέλυκα'],['Perfect middle/passive','λέλυμαι'],['Aorist passive','ἐλύθην']])]}
  ];
  const hebPersons = ['3ms','3fs','2ms','2fs','1cs','3mp','3fp','2mp','2fp','1cp'];
  const hebrewForms = {
    Qal:[['כָּתַב','כָּתְבָה','כָּתַבְתָּ','כָּתַבְתְּ','כָּתַבְתִּי','כָּתְבוּ','כָּתְבוּ','כְּתַבְתֶּם','כְּתַבְתֶּן','כָּתַבְנוּ'],['יִכְתֹּב','תִּכְתֹּב','תִּכְתֹּב','תִּכְתְּבִי','אֶכְתֹּב','יִכְתְּבוּ','תִּכְתֹּבְנָה','תִּכְתְּבוּ','תִּכְתֹּבְנָה','נִכְתֹּב']],
    Niphal:[['נִכְתַּב','נִכְתְּבָה','נִכְתַּבְתָּ','נִכְתַּבְתְּ','נִכְתַּבְתִּי','נִכְתְּבוּ','נִכְתְּבוּ','נִכְתַּבְתֶּם','נִכְתַּבְתֶּן','נִכְתַּבְנוּ'],['יִכָּתֵב','תִּכָּתֵב','תִּכָּתֵב','תִּכָּתְבִי','אִכָּתֵב','יִכָּתְבוּ','תִּכָּתַבְנָה','תִּכָּתְבוּ','תִּכָּתַבְנָה','נִכָּתֵב']],
    Piel:[['כִּתֵּב','כִּתְּבָה','כִּתַּבְתָּ','כִּתַּבְתְּ','כִּתַּבְתִּי','כִּתְּבוּ','כִּתְּבוּ','כִּתַּבְתֶּם','כִּתַּבְתֶּן','כִּתַּבְנוּ'],['יְכַתֵּב','תְּכַתֵּב','תְּכַתֵּב','תְּכַתְּבִי','אֲכַתֵּב','יְכַתְּבוּ','תְּכַתֵּבְנָה','תְּכַתְּבוּ','תְּכַתֵּבְנָה','נְכַתֵּב']],
  };
  hebrewForms.Pual=hebrewForms.Piel; hebrewForms.Hiphil=hebrewForms.Piel; hebrewForms.Hophal=hebrewForms.Niphal; hebrewForms.Hitpael=hebrewForms.Piel;
  const hebrewTabs = stem => [{id:'perfect',label:'Perfect',charts:[chart(`${stem} Perfect: כתב`, ['Person',...hebPersons], [['Form',...hebrewForms[stem][0]]])]}, {id:'imperfect',label:'Imperfect',charts:[chart(`${stem} Imperfect: כתב`, ['Person',...hebPersons], [['Form',...hebrewForms[stem][1]]])]}, {id:'imperative',label:'Imperative',charts:[chart(`${stem} Imperative`, ['2ms','2fs','2mp','2fp'], [['Form','כְּתֹב','כִּתְבִי','כִּתְבוּ','כְּתֹבְנָה']])]}, {id:'infinitive-construct',label:'Infinitive Construct',charts:[chart(`${stem} Infinitive Construct`, ['Form'], [[stem==='Hiphil'?'הַכְתִּיב':'כְּתֹב']])]}, {id:'infinitive-absolute',label:'Infinitive Absolute',charts:[chart(`${stem} Infinitive Absolute`, ['Form'], [[stem==='Hiphil'?'הַכְתֵּב':'כָּתוֹב']])]}, {id:'participles',label:'Participles',charts:[chart(`${stem} Participles`, ['Gender/Number','Form'], [['masculine singular','כֹּתֵב'],['feminine singular','כֹּתֶבֶת'],['masculine plural','כֹּתְבִים'],['feminine plural','כֹּתְבוֹת']])]}, {id:'recognition',label:'Recognition',charts:[chart(`${stem} recognition`, ['Clue','Tip'], [[stemInfo[stem][1], stemInfo[stem][2]],['Root','כתב']])]}];
  const decoderEntries = {
    'V-PAI-3S': { breakdown:['Verb','Present Active Indicative','3rd singular'], tips:['Look for present stem plus active ending.'], examples:['λύει'], related:['greek-lyo-paradigm','greek-verb-endings'] },
    'V-API-3S': { breakdown:['Verb','Aorist Passive Indicative','3rd singular'], tips:['Augment plus θη commonly marks aorist passive.'], examples:['ἐλύθη'], related:['greek-lyo-paradigm','greek-common-parsing-clues'] },
    'V-AAI-1P': { breakdown:['Verb','Aorist Active Indicative','1st plural'], tips:['Augment plus σα often marks first aorist.'], examples:['ἐλύσαμεν'], related:['greek-lyo-paradigm','greek-common-parsing-clues'] },
    'N-GSM': { breakdown:['Noun','Genitive Singular Masculine'], tips:['ου is a common second-declension genitive clue.'], examples:['λόγου'], related:['greek-logos-paradigm','greek-noun-endings'] },
    'A-NSF': { breakdown:['Adjective','Nominative Singular Feminine'], tips:['Adjectives agree with nouns they modify.'], examples:['καλή'], related:['greek-kalos-paradigm'] },
    'QAL PERFECT 3MS': { breakdown:['Qal stem','Perfect conjugation','3ms'], tips:['Basic stem; perfect 3ms is often the lexical baseline.'], examples:['כָּתַב'], related:['hebrew-qal'] },
    'HIPHIL IMPERFECT 2MP': { breakdown:['Hiphil stem','Imperfect conjugation','2mp'], tips:['Look for causative ה/י pattern and 2mp ending וּ.'], examples:['תַּכְתִּיבוּ'], related:['hebrew-hiphil','hebrew-prefixes'] }
  };

  const topics = [
    { id:'grammar-parsing-decoder', language:'greek', title:'Parsing Decoder', category:'Tools', summary:'Lookup helper that opens the interactive parsing decoder for Greek and Hebrew parsing codes.', body:['Use this entry to open the existing Parsing Decoder UI from Grammar search results.'], recognitionTips:['Search for parsing decoder when you need to interpret a parsing code.'], charts:[], examples:[ex('V-AAI-1P','Parsing code','Aorist active indicative, first plural'), ex('Hiphil Imperfect 2mp','Parsing code','Hiphil imperfect, second masculine plural')], related:['greek-common-parsing-clues','greek-verb-endings','hebrew-stem-markers'] },
    { id:'greek-articles', language:'greek', title:'Article Endings', category:'Article Paradigms', summary:'The Greek article marks case, number, and gender and often identifies a noun as definite or previously known.', body:['Articles are parsing anchors: parse the article and you often know the nearby noun pattern.'], recognitionTips:['ὁ/οἱ often point to masculine nominative forms.','τοῦ/τῶν are strong genitive clues.','τό can be nominative or accusative neuter singular.'], charts:[chart('Greek article chart', ['Case','Masculine','Feminine','Neuter'], [['Nom sg','ὁ','ἡ','τό'],['Gen sg','τοῦ','τῆς','τοῦ'],['Dat sg','τῷ','τῇ','τῷ'],['Acc sg','τόν','τήν','τό'],['Nom pl','οἱ','αἱ','τά'],['Gen pl','τῶν','τῶν','τῶν'],['Dat pl','τοῖς','ταῖς','τοῖς'],['Acc pl','τούς','τάς','τά']], { color:'blue', note:'The article agrees with its noun.' })], examples:[ex('ὁ λόγος','John 1:1','the Word'), ex('τὰ ἔργα','James 2:18','the works')], related:['greek-logos-paradigm','greek-noun-endings','greek-pronouns'] },
    { id:'greek-pronouns', language:'greek', title:'Pronoun Endings', category:'Pronoun Paradigms', summary:'Pronouns replace or point to nouns and are parsed for case, number, gender, and sometimes person.', body:['Pronouns must be read in context because their antecedent may be nearby or implied.'], recognitionTips:['αὐτός may function as he/she/it, self, or same.','Relative pronouns often introduce dependent clauses.'], charts:[chart('Personal pronouns', ['Person','Nominative','Genitive','Accusative'], [['1 sg','ἐγώ','μου / ἐμοῦ','με / ἐμέ'],['2 sg','σύ','σου / σοῦ','σε / σέ'],['3 masc sg','αὐτός','αὐτοῦ','αὐτόν']])], examples:[ex('αὐτός','Matthew 1:21','he'), ex('ἐγώ','John 8:32','I')], related:['greek-articles','greek-noun-endings'] },
    { id:'greek-verb-overview', language:'greek', title:'Verb overview', category:'Verbs', summary:'Greek verbs communicate action or state through tense-form, voice, mood, person, and number.', body:['Start with tense-form, voice, and mood, then confirm person and number from endings.'], recognitionTips:['Personal endings carry person and number.','Augment often points to past indicative forms.','Connecting vowels often appear before endings.'], charts:[chart('Main parsing categories', ['Category','Question'], [['Tense-form','What viewpoint/time?'],['Voice','How is the subject related?'],['Mood','How is the action presented?']], { color:'tense' }), greekVerbChart], examples:[ex('λύω','John 8:32','I release / loose'), ex('λέγω','Matthew 5:37','I say')], related:['greek-tense-explanations','greek-voice-explanations','greek-mood-explanations','greek-lyo-paradigm','greek-verb-endings'] },
    { id:'greek-tense-explanations', language:'greek', title:'Tense explanations', category:'Verbs', color:'tense', frequency:'Present and aorist are very common tense-forms.', summary:'Greek tense-forms combine aspect with time most clearly in the indicative mood.', body:['Present/imperfect usually present imperfective aspect; aorist usually presents perfective aspect; perfect emphasizes a resulting state.'], recognitionTips:['Present often uses the present stem plus primary endings.','Aorist often has augment and σα or second-aorist stem changes.'], charts:[chart('Greek tense-form overview', ['Tense-form','Typical force'], [['Present','ongoing/imperfective'],['Imperfect','past ongoing'],['Aorist','summary/perfective'],['Perfect','completed with result'],['Future','future-oriented']], { color:'tense' })], examples:[ex('λύω','John 8:32','I release'), ex('λέγω','Matthew 5:37','I say')], related:['greek-verb-overview','greek-voice-explanations','greek-mood-explanations'] },
    { id:'greek-voice-explanations', language:'greek', title:'Voice explanations', category:'Verbs', color:'voice', summary:'Voice describes the subject’s relationship to the action.', body:['Active presents the subject acting; passive presents the subject acted upon; middle highlights subject involvement.'], recognitionTips:['μαι/σαι/ται endings often mark middle/passive forms.','θη often points to aorist passive.'], charts:[chart('Voice overview', ['Voice','Basic idea'], [['Active','subject acts'],['Middle','subject participates'],['Passive','subject receives action']], { color:'voice' })], examples:[ex('λύεται','Mark 7:35','is loosed/opened'), ex('ἐλήμφθην','Representative','I was taken')], related:['greek-verb-overview','greek-tense-explanations','greek-mood-explanations'] },
    { id:'greek-mood-explanations', language:'greek', title:'Mood explanations', category:'Verbs', color:'mood', frequency:'Indicative mood ≈ most finite verbs.', summary:'Mood presents action as assertion, possibility, command, verbal idea, or adjectival verbal form.', body:['Indicative states or asks; subjunctive often presents potential/purpose; imperative commands.'], recognitionTips:['ωμεν/ητε can mark subjunctive endings.','Imperatives often lack an explicit subject.'], charts:[chart('Mood overview', ['Mood','Common use'], [['Indicative','statement/question'],['Subjunctive','potential/purpose'],['Imperative','command'],['Infinitive','verbal noun'],['Participle','verbal adjective']], { color:'mood' })], examples:[ex('λέγει','Matthew 5:37','he says'), ex('πιστεύωμεν','Representative','let us believe')], related:['greek-verb-overview','greek-tense-explanations','greek-voice-explanations'] },
    { id:'greek-noun-endings', language:'greek', title:'Noun endings cheat sheet', category:'Cheat sheets', summary:'Common noun endings help students recognize case and number quickly.', body:['Use endings as clues, then confirm with article, adjective agreement, and context.'], recognitionTips:['ος → often nominative masculine singular.','ου → often genitive singular.','οι → often nominative masculine plural.','ον → often accusative masculine singular or neuter nominative/accusative singular.'], charts:[chart('Common noun ending clues', ['Ending','Likely parse','Example'], [['ος','nominative masculine singular','λόγος'],['ου','genitive singular','λόγου'],['ῳ','dative singular','λόγῳ'],['ον','accusative masculine singular','λόγον'],['οι','nominative masculine plural','λόγοι']])], examples:[ex('λόγος','John 1:1','word'), ex('λόγου','John 1:14','of a word / word')], related:['greek-logos-paradigm','greek-articles'] },
    { id:'greek-verb-endings', language:'greek', title:'Verb endings cheat sheet', category:'Cheat sheets', summary:'Common verb endings give quick person, number, voice, and mood clues.', body:['Endings are pattern-recognition aids, not a substitute for context.'], recognitionTips:['ω endings often mark first singular active.','ει endings often mark third singular active.','ουσι endings often mark third plural active.'], charts:[greekVerbChart], examples:[ex('λύω','John 8:32','I release'), ex('λέγω','Matthew 5:37','I say')], related:['greek-lyo-paradigm','greek-verb-overview'] },
    { id:'greek-common-parsing-clues', language:'greek', title:'Common parsing clues', category:'Cheat sheets', summary:'A compact checklist for recognizing common Greek forms.', body:['Look for articles, augments, endings, stem changes, and prepositional contexts.'], recognitionTips:['Augment ε often points to past indicative.','θη often points to passive.','σ before endings may signal future or first aorist.'], charts:[chart('Parsing clue checklist', ['Clue','Often indicates'], [['ε augment','past indicative'],['θη','aorist passive'],['σ + ending','future or first aorist'],['μαι/σαι/ται','middle/passive']])], examples:[ex('ἐλήμφθην','Representative','I was taken')], related:['greek-tense-explanations','greek-voice-explanations'] },
    { id:'greek-lyo-paradigm', language:'greek', title:'Verb Paradigms', category:'Verb Paradigms', summary:'Representative Greek omega-verb paradigm with principal parts.', body:['This is an educational reference page for recognizing regular omega-verb patterns.'], principalParts:['λύω','λύσω','ἔλυσα','λέλυκα','λέλυμαι','ἐλύθην'], paradigmTabs:greekLyoTabs, breadcrumbs:['Grammar','Greek','Verb Paradigms'], recognitionTips:['Present active indicative uses ω, εις, ει, ομεν, ετε, ουσι.','Middle/passive forms often use μαι endings.'], charts:[greekVerbChart, chart('Principal parts', ['Part','Form'], [['Present','λύω'],['Future active','λύσω'],['Aorist active','ἔλυσα'],['Perfect active','λέλυκα'],['Perfect middle/passive','λέλυμαι'],['Aorist passive','ἐλύθην']])], examples:[ex('λύω','John 8:32','I release / loose')], related:['greek-verb-endings','greek-verb-overview'] },
    { id:'greek-logos-paradigm', language:'greek', title:'Noun Paradigms', category:'Noun Paradigms', summary:'Representative second-declension masculine noun paradigm.', body:['λόγος illustrates many common second-declension noun endings.'], recognitionTips:['ος is a common nominative singular ending.','ου is a common genitive singular ending.'], breadcrumbs:['Grammar','Greek','Noun Paradigms'], charts:[chart('λόγος noun paradigm', ['Case','Singular','Plural'], [['Nominative','λόγος','λόγοι'],['Genitive','λόγου','λόγων'],['Dative','λόγῳ','λόγοις'],['Accusative','λόγον','λόγους'],['Vocative','λόγε','λόγοι']])], examples:[ex('λόγος','John 1:1','word')], related:['greek-noun-endings','greek-articles'] },
    { id:'greek-kalos-paradigm', language:'greek', title:'Adjective Paradigms', category:'Adjective Paradigms', summary:'Representative 2-1-2 adjective paradigm.', body:['καλός illustrates adjective agreement across masculine, feminine, and neuter forms.'], recognitionTips:['Adjectives agree with nouns in case, number, and gender.','Neuter nominative and accusative forms often match.'], breadcrumbs:['Grammar','Greek','Adjective Paradigms'], charts:[chart('καλός masculine', ['Case','Singular','Plural'], [['Nominative','καλός','καλοί'],['Genitive','καλοῦ','καλῶν'],['Dative','καλῷ','καλοῖς'],['Accusative','καλόν','καλούς']]), chart('καλή feminine', ['Case','Singular','Plural'], [['Nominative','καλή','καλαί'],['Genitive','καλῆς','καλῶν'],['Dative','καλῇ','καλαῖς'],['Accusative','καλήν','καλάς']]), chart('καλόν neuter', ['Case','Singular','Plural'], [['Nominative','καλόν','καλά'],['Genitive','καλοῦ','καλῶν'],['Dative','καλῷ','καλοῖς'],['Accusative','καλόν','καλά']])], examples:[ex('καλός','John 10:11','good')], related:['greek-articles','greek-noun-endings'] },
    { id:'hebrew-pronouns', language:'hebrew', title:'Pronouns', category:'Nominals', summary:'Hebrew pronouns mark person, gender, and number and may stand alone or attach as suffixes.', body:['Independent pronouns often supply emphasis or serve as subjects in verbless clauses.'], recognitionTips:['הוּא is 3ms; הִיא is 3fs.','Suffixes attach to nouns, prepositions, and verbs.'], charts:[chart('Independent pronouns', ['Person','Singular','Plural'], [['1 common','אֲנִי / אָנֹכִי','אֲנַחְנוּ'],['2 masculine','אַתָּה','אַתֶּם'],['2 feminine','אַתְּ','אַתֶּן'],['3 masculine','הוּא','הֵם'],['3 feminine','הִיא','הֵנָּה']])], examples:[ex('אֲנִי','Exodus 20:2','I'), ex('הוּא','Genesis 2:11','it / he')], related:['hebrew-suffixes','hebrew-noun-basics'] },
    { id:'hebrew-noun-basics', language:'hebrew', title:'Noun patterns / noun basics', category:'Nominals', summary:'Hebrew nouns have gender, number, and state; construct chains are central to noun syntax.', body:['The construct state links one noun closely to a following noun, often translated with “of.”'], recognitionTips:['־ִים often marks masculine plural.','־וֹת often marks feminine plural.','Construct nouns are bound closely to the following noun.'], charts:[chart('Noun pattern clues', ['Feature','Common marker'], [['Masculine plural','־ִים'],['Feminine singular','־ָה / ־ת'],['Feminine plural','־וֹת'],['Construct','bound form before another noun']])], examples:[ex('דְּבַר יְהוָה','Jeremiah 1:2','word of YHWH'), ex('סוּסִים','Representative','horses')], related:['hebrew-pronouns','hebrew-suffixes'] },
    { id:'hebrew-prefixes', language:'hebrew', title:'Prefixes cheat sheet', category:'Cheat sheets', summary:'Common Hebrew prefixes help identify conjunctions, prepositions, articles, and verbal forms.', body:['Prefixes stack, so identify each element from left to right.'], recognitionTips:['וַי → wayyiqtol narrative form.','הִ → often Hiphil in the right verbal context.','לְ, בְּ, כְּ attach directly to words.'], charts:[chart('Common prefixes', ['Prefix','Recognition'], [['וַי','wayyiqtol'],['הִ','Hiphil clue'],['נִ','Niphal clue'],['הַ','article or interrogative depending context'],['לְ','to/for or infinitive marker']])], examples:[ex('וַיֹּאמֶר','Genesis 1:3','and he said')], related:['hebrew-wayyiqtol','hebrew-stem-markers'] },
    { id:'hebrew-suffixes', language:'hebrew', title:'Suffixes cheat sheet', category:'Cheat sheets', summary:'Hebrew suffixes mark pronominal relationships and some verbal parsing information.', body:['Suffixes can show possession, objects, or verbal person/number/gender.'], recognitionTips:['וֹ often marks his/its on nouns.','תִּי often marks first common singular perfect.'], charts:[chart('Common suffix clues', ['Suffix','Often indicates'], [['וֹ','his/its'],['ךָ','your masculine singular'],['תִּי','I, perfect'],['וּ','they or plural marker depending form']])], examples:[ex('סוּסוֹ','Representative','his horse')], related:['hebrew-pronouns'] },
    { id:'hebrew-wayyiqtol', language:'hebrew', title:'Wayyiqtol recognition', category:'Cheat sheets', summary:'Wayyiqtol is a common Biblical Hebrew narrative sequence form.', body:['Wayyiqtol often advances narrative with “and he/they ...” in past-time contexts.'], recognitionTips:['וַי is the key visual clue.','Look for doubled prefix consonant when spelling allows.','Translate according to narrative context, not mechanically.'], charts:[chart('Wayyiqtol clues', ['Clue','Example'], [['וַי + imperfect','וַיֹּאמֶר'],['Narrative sequence','and he said / then he said']])], examples:[ex('וַיֹּאמֶר','Genesis 1:3','and he said')], related:['hebrew-prefixes','hebrew-qal'] },
    { id:'hebrew-stem-markers', language:'hebrew', title:'Stem markers cheat sheet', category:'Cheat sheets', summary:'Quick recognition markers for the major Hebrew stems.', body:['Use consonants, vowels, and meaning together to identify a stem.'], recognitionTips:['נִ often points to Niphal.','Doubled middle radical often points to Piel/Pual/Hitpael.','הִ often points to Hiphil.'], charts:[chart('Stem marker overview', ['Stem','Marker','Typical relationship'], Object.entries(stemInfo).map(([s,v])=>[s,v[1],v[0]]))], examples:[ex('הִכְתִּיב','Representative','he caused to write')], related:['hebrew-qal','hebrew-niphal','hebrew-piel','hebrew-hiphil'] },
    ...['Qal','Niphal','Piel','Pual','Hiphil','Hophal','Hitpael'].map(hebrewStemTopic),
    { id:'hebrew-katav-stem-relationships', language:'hebrew', title:'כתב stem relationships', category:'Paradigms', summary:'A single-root overview showing how כתב relates across major Hebrew stems.', body:['This page compares stem relationships without generating forms dynamically.'], recognitionTips:['Start with the root consonants כ־ת־ב.','Then identify stem markers around the root.'], charts:[chart('כתב across stems', ['Stem','Relationship','Representative pattern'], Object.entries(stemInfo).map(([s,v])=>[s,v[0],v[1]]))], examples:[ex('אָמַר','Genesis 1:3','he said'), ex('כתב','Jeremiah 36:2','write')], stemRelationships:{ root:'כתב', stems:['Qal','Niphal','Piel','Pual','Hiphil','Hophal','Hitpael'], explanation:stemRelationships }, related:['hebrew-qal','hebrew-niphal','hebrew-piel','hebrew-pual','hebrew-hiphil','hebrew-hophal','hebrew-hitpael'] }
  ];


  const caseRows = [['Nominative','subject / predicate nominative'],['Genitive','of / from / possession'],['Dative','to / for / in / by'],['Accusative','direct object / extent'],['Vocative','direct address']];
  const greekCaseEndingTopics = [
    { id:'greek-first-declension-endings', language:'greek', title:'First Declension', category:'Noun Paradigms', summary:'Quick chart for common first-declension case endings, especially feminine nouns.', body:['Use this page as an ending lookup; fuller case functions live on the shared Case Functions page.'], recognitionTips:['η/α often marks nominative singular feminine.','ης/ας often marks genitive singular.','αι often marks nominative plural.'], charts:[chart('First declension endings', ['Case','Singular','Plural','Common clue'], [['Nominative','-η / -α','-αι','subject'],['Genitive','-ης / -ας','-ῶν','of'],['Dative','-ῃ / -ᾳ','-αις','to/for/in'],['Accusative','-ην / -αν','-ας','object'],['Vocative','-η / -α','-αι','address']])], examples:[ex('γραφή','2 Timothy 3:16','Scripture'), ex('δόξα','John 1:14','glory')], related:['greek-case-functions','greek-noun-endings','greek-article-endings'] },
    { id:'greek-second-declension-endings', language:'greek', title:'Second Declension', category:'Noun Paradigms', summary:'Quick chart for common second-declension masculine and neuter endings.', body:['Second declension endings are among the most frequent nominal forms in the Greek New Testament.'], recognitionTips:['ος is often nominative masculine singular.','ου is a strong genitive singular clue.','Neuter nominative and accusative match.'], charts:[chart('Second declension endings', ['Case','Masculine sg/pl','Neuter sg/pl','Common clue'], [['Nominative','-ος / -οι','-ον / -α','subject'],['Genitive','-ου / -ων','-ου / -ων','of'],['Dative','-ῳ / -οις','-ῳ / -οις','to/for/in'],['Accusative','-ον / -ους','-ον / -α','object'],['Vocative','-ε / -οι','-ον / -α','address']])], examples:[ex('λόγος','John 1:1','word'), ex('ἔργον','James 2:18','work')], related:['greek-case-functions','greek-noun-endings','greek-logos-paradigm'] },
    { id:'greek-third-declension-basics', language:'greek', title:'Third Declension Basics', category:'Noun Paradigms', summary:'Concise third-declension lookup for frequent case endings and stem changes.', body:['Third declension nouns vary by stem, so identify the genitive singular and compare the article and context.'], recognitionTips:['Genitive singular -ος is the best anchor.','Dative plural often ends in -σι(ν).','Nominative singular may be irregular or bare stem.'], charts:[chart('Third declension basic endings', ['Case','Singular','Plural','Common clue'], [['Nominative','varies / -ς','-ες / -α','subject'],['Genitive','-ος','-ων','of'],['Dative','-ι','-σι(ν)','to/for/in'],['Accusative','-α / -ν','-ας / -α','object'],['Vocative','varies','-ες / -α','address']])], examples:[ex('σάρξ','John 1:14','flesh'), ex('ὄνομα','Matthew 1:21','name')], related:['greek-case-functions','greek-noun-endings','greek-article-endings'] },
    { id:'greek-article-endings', language:'greek', title:'Article Endings', category:'Article Paradigms', summary:'Dedicated article ending page for quick agreement checks.', body:['Articles are often the fastest way to confirm case, number, and gender.'], recognitionTips:['Parse the article before guessing a nearby noun.','τοῦ/τῶν are common genitive anchors.'], charts:[chart('Article endings', ['Case','Masculine sg/pl','Feminine sg/pl','Neuter sg/pl'], [['Nominative','ὁ / οἱ','ἡ / αἱ','τό / τά'],['Genitive','τοῦ / τῶν','τῆς / τῶν','τοῦ / τῶν'],['Dative','τῷ / τοῖς','τῇ / ταῖς','τῷ / τοῖς'],['Accusative','τόν / τούς','τήν / τάς','τό / τά'],['Vocative','—','—','—']])], examples:[ex('ὁ λόγος','John 1:1','the Word')], related:['greek-articles','greek-case-functions','greek-pronoun-endings'] },
    { id:'greek-adjective-endings', language:'greek', title:'Adjective Endings', category:'Adjective Paradigms', summary:'Common 2-1-2 adjective endings for agreement lookup.', body:['Adjectives agree with the nouns they modify in case, number, and gender.'], recognitionTips:['Find the noun or substantive use that controls agreement.','Neuter nominative and accusative forms often match.'], charts:[chart('Adjective endings', ['Case','Masculine sg/pl','Feminine sg/pl','Neuter sg/pl'], [['Nominative','-ος / -οι','-η / -αι','-ον / -α'],['Genitive','-ου / -ων','-ης / -ων','-ου / -ων'],['Dative','-ῳ / -οις','-ῃ / -αις','-ῳ / -οις'],['Accusative','-ον / -ους','-ην / -ας','-ον / -α'],['Vocative','-ε / -οι','-η / -αι','-ον / -α']])], examples:[ex('καλός','John 10:11','good')], related:['greek-kalos-paradigm','greek-case-functions','greek-article-endings'] },
    { id:'greek-pronoun-endings', language:'greek', title:'Pronoun Endings', category:'Pronoun Paradigms', summary:'Fast lookup for major Greek pronoun families.', body:['Pronouns are often small but decisive for tracking participants and clauses.'], recognitionTips:['Relative pronouns usually introduce a clause.','Demonstratives point near/far and agree with their referent.'], charts:[chart('Pronoun family index', ['Family','Key forms','Lookup page'], [['Personal','ἐγώ, σύ, αὐτός','Pronouns'],['Demonstrative','οὗτος, ἐκεῖνος','Pronouns'],['Relative','ὅς, ἥ, ὅ','Pronouns'],['Interrogative','τίς / τί','Pronouns']])], examples:[ex('ὅς','John 1:15','who'), ex('τίς','Matthew 21:10','who?')], related:['greek-pronouns','greek-case-functions','greek-article-endings'] }
  ];

  const grammarRefinements = [
    ...greekCaseEndingTopics,
    { id:'greek-case-functions', language:'greek', title:'Case Functions', category:'Shared Explanations', summary:'One shared page for common Greek case functions used by noun, article, adjective, and pronoun pages.', body:['Start with the form, then ask how the case functions in context. Avoid repeating these case summaries on every paradigm page.'], recognitionTips:['Articles and adjectives usually confirm a noun’s case.','Prepositions can narrow the likely case function.'], charts:[chart('Case function quick guide', ['Case','Frequent reading use'], caseRows)], examples:[ex('τοῦ θεοῦ','John 1:1','of God'), ex('τῷ κυρίῳ','Representative','to/for the Lord')], related:['greek-first-declension-endings','greek-second-declension-endings','greek-third-declension-basics','greek-article-endings'] },
    { id:'greek-participles', language:'greek', title:'Participles', category:'Verb Paradigms', summary:'Concise Greek participle reference for frequent tense-voice patterns.', body:['Participles are verbal adjectives. Parse tense-form and voice, then check case, number, and gender agreement.'], recognitionTips:['-ων/-ουσα/-ον often marks present active.','-μενος/-μενη/-μενον often marks middle/passive.','-σας/-σασα/-σαν marks many aorist active participles; -θείς often marks aorist passive.'], charts:[chart('Participle recognition patterns', ['Tense/Voice','Masc nom sg','Fem nom sg','Neut nom sg','Common clue'], [['Present active','λύων','λύουσα','λῦον','οντ / ουσα'],['Present middle/passive','λυόμενος','λυομένη','λυόμενον','μενος'],['Aorist active','λύσας','λύσασα','λῦσαν','σας'],['Aorist middle','λυσάμενος','λυσαμένη','λυσάμενον','σαμενος'],['Aorist passive','λυθείς','λυθεῖσα','λυθέν','θείς / θεν'],['Perfect active','λελυκώς','λελυκυῖα','λελυκός','κως / κοτ'],['Perfect middle/passive','λελυμένος','λελυμένη','λελυμένον','μενος with reduplication']])], examples:[ex('λέγων','Matthew 3:2','saying'), ex('γεγραμμένον','Matthew 4:4','written')], related:['greek-lyo-paradigm','greek-voice-explanations','greek-case-functions'] },
    { id:'greek-contract-verbs', language:'greek', title:'Contract Verbs', category:'Verb Paradigms', summary:'Recognition guide for alpha, epsilon, and omicron contract verbs.', body:['Contract verbs combine a stem-final vowel with endings. The goal here is recognition, not a morphology engine.'], recognitionTips:['Alpha contracts often show ᾶ/ᾳ forms.','Epsilon contracts often show ει or ου after contraction.','Omicron contracts often show ου/οι forms.'], charts:[chart('Contract verb clues', ['Type','Representative','Common contracted clue'], [['Alpha contract','ἀγαπάω → ἀγαπῶ','α + ω/εις contracts'],['Epsilon contract','ποιέω → ποιῶ','ε + ο often → ου'],['Omicron contract','δηλόω → δηλῶ','ο + ο/ε often → ου/οι']])], examples:[ex('ἀγαπᾷ','John 3:35','he loves'), ex('ποιεῖ','Matthew 7:21','he does')], related:['greek-verb-overview','greek-verb-endings','greek-common-parsing-clues'] },
    { id:'greek-mi-verbs-hook', language:'greek', title:'μι Verbs (Future Hook)', category:'Future Hooks', summary:'Placeholder for a future authored reference on μι verbs.', body:['Future expansion hook only. This keeps navigation ready without adding incomplete paradigms.'], recognitionTips:['μι endings and athematic patterns need a dedicated page later.'], charts:[], examples:[ex('δίδωμι','Representative','I give')], related:['greek-verb-overview','greek-common-parsing-clues'] },
    { id:'greek-irregular-verbs-hook', language:'greek', title:'Irregular Verbs (Future Hook)', category:'Future Hooks', summary:'Placeholder for a future authored reference on common irregular verbs.', body:['Future expansion hook only; no generated irregular morphology is implemented.'], recognitionTips:['Principal parts are the safest entry point for irregular verbs.'], charts:[], examples:[ex('ἔρχομαι','Representative','I come/go')], related:['greek-verb-overview','greek-tense-explanations'] },
    { id:'hebrew-dual-forms', language:'hebrew', title:'Dual Forms', category:'Nominals', summary:'Quick guide to Hebrew singular, plural, and dual forms.', body:['The dual often marks pairs, especially body parts and time expressions.'], recognitionTips:['־ַיִם is the common dual ending.','Expect duals with eyes, hands, feet, ears, days, and years.'], charts:[chart('Number forms', ['Number','Typical marker','Example'], [['Singular','no plural/dual ending','יָד hand'],['Plural','־ִים / ־וֹת','סוּסִים horses'],['Dual','־ַיִם','יָדַיִם hands / two hands']])], examples:[ex('יָדַיִם','Representative','hands'), ex('יוֹמַיִם','Representative','two days')], related:['hebrew-noun-basics','hebrew-construct-chains','hebrew-suffixes'] },
    { id:'hebrew-pronominal-suffixes', language:'hebrew', title:'Pronominal Suffixes', category:'Nominals', summary:'Dedicated suffix chart for possession and object relationships.', body:['Suffixes attach to nouns, prepositions, and verbs. On nouns they often express possession.'], recognitionTips:['וֹ often means his/its.','ךָ and ךְ distinguish your masculine/feminine singular.','Construct chains and suffixes both express close noun relationships.'], charts:[chart('Common noun suffixes', ['Person','Suffix','Example','Sense'], [['1cs','־ִי','סוּסִי','my horse'],['2ms','־ךָ','סוּסְךָ','your horse'],['2fs','־ךְ','סוּסֵךְ','your horse'],['3ms','־וֹ','סוּסוֹ','his horse'],['3fs','־הּ','סוּסָהּ','her horse'],['1cp','־נוּ','סוּסֵנוּ','our horse'],['3mp','־הֶם','סוּסֵיהֶם','their horse']])], examples:[ex('סוּסוֹ','Representative','his horse'), ex('עַמִּי','Exodus 3:10','my people')], related:['hebrew-suffixes','hebrew-construct-chains','hebrew-pronouns'] },
    { id:'hebrew-construct-chains', language:'hebrew', title:'Construct Chains', category:'Nominals', summary:'Concise reference for absolute state, construct state, and noun chains.', body:['A construct noun is bound to the following noun. Translate many chains with “of,” then refine by context.'], recognitionTips:['The construct word normally cannot take the article; definiteness often comes from the final noun.','Construct forms may shorten vowels or change endings.'], charts:[chart('Construct chain basics', ['Feature','Description','Example'], [['Absolute state','noun stands independently','דָּבָר word'],['Construct state','noun bound to following noun','דְּבַר word of'],['Chain','construct + following noun(s)','דְּבַר יְהוָה word of YHWH']])], examples:[ex('דְּבַר יְהוָה','Jeremiah 1:2','word of YHWH'), ex('בְּנֵי יִשְׂרָאֵל','Exodus 1:1','sons of Israel')], related:['hebrew-noun-basics','hebrew-pronominal-suffixes','hebrew-dual-forms'] },
    { id:'hebrew-weak-verbs', language:'hebrew', title:'Weak Verb Overview', category:'Verbs', summary:'Recognition-only guide for common weak verbs and weak verb classes.', body:['This page does not implement weak verb paradigms. It flags patterns Bible readers often meet.'], recognitionTips:['I-נ verbs may assimilate nun.','III-ה verbs often show final ה/י changes.','Hollow verbs have a weak middle radical; geminate verbs repeat the second and third radicals.'], charts:[chart('Weak verb classes', ['Class','Recognition pattern','Future status'], [['I-נ','initial nun may disappear into doubling','future authored page'],['III-ה','final ה changes or drops in some forms','future authored page'],['Hollow','middle ו/י vowel behavior','future authored page'],['Geminate','second and third radicals match','future authored page']])], examples:[ex('נפל','Representative','fall (I-נ)'), ex('בנה','Representative','build (III-ה)')], related:['hebrew-stem-markers','hebrew-qal','hebrew-prefixes'] },
    { id:'grammar-parsing-ambiguity', language:'greek', title:'Parsing Ambiguity Guide', category:'Tools', summary:'What to do when a form could parse more than one way.', body:['Do not decide from endings alone. Check context, articles, agreement, nearby verbs, and common pitfalls.'], recognitionTips:['Articles often settle nominal case, gender, and number.','Agreement links adjectives, participles, and pronouns to their heads.','Context can decide whether a form is middle or passive, subject or object, or noun or adjective.'], charts:[chart('Ambiguity checklist', ['Question','Use it for'], [['Is there an article?','case/gender/number anchor'],['What agrees with it?','adjectives, pronouns, participles'],['What does context require?','subject/object and voice decisions'],['Is this a common look-alike?','neuter nom/acc, middle/passive, genitive forms']])], examples:[ex('τό','Representative','nominative or accusative neuter singular'), ex('αὐτοῦ','Representative','his/of him/of it')], related:['greek-case-functions','greek-article-endings','greek-pronouns','hebrew-construct-chains'] }
  ];
  topics.push(...grammarRefinements);
  const suffixTopic = topics.find(t => t.id === 'hebrew-suffixes');
  if (suffixTopic) suffixTopic.related = Array.from(new Set([...(suffixTopic.related||[]), 'hebrew-pronominal-suffixes', 'hebrew-construct-chains']));
  const nounTopic = topics.find(t => t.id === 'hebrew-noun-basics');
  if (nounTopic) nounTopic.related = Array.from(new Set([...(nounTopic.related||[]), 'hebrew-dual-forms', 'hebrew-construct-chains']));
  const pronounTopic = topics.find(t => t.id === 'greek-pronouns');
  if (pronounTopic) {
    pronounTopic.charts.push(
      chart('Demonstrative pronouns', ['Pronoun','Masculine','Feminine','Neuter','Use'], [['near demonstrative','οὗτος','αὕτη','τοῦτο','this/these'],['far demonstrative','ἐκεῖνος','ἐκείνη','ἐκεῖνο','that/those']]),
      chart('Relative pronoun', ['Case','Masculine','Feminine','Neuter'], [['Nominative','ὅς','ἥ','ὅ'],['Genitive','οὗ','ἧς','οὗ'],['Dative','ᾧ','ᾗ','ᾧ'],['Accusative','ὅν','ἥν','ὅ']]),
      chart('Interrogative pronoun', ['Case','Masculine/Feminine','Neuter'], [['Nominative','τίς','τί'],['Genitive','τίνος','τίνος'],['Dative','τίνι','τίνι'],['Accusative','τίνα','τί']])
    );
    pronounTopic.related = Array.from(new Set([...(pronounTopic.related||[]), 'greek-pronoun-endings', 'greek-case-functions']));
  }

  function topicLabel(id){ return topics.find(t => t.id === id)?.title || id; }
  function cellText(cell){ return typeof cell === 'object' && cell !== null ? Object.values(cell).join(' ') : String(cell ?? ''); }
  function normalizeSearchText(value){ return String(value ?? '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase(); }
  function flattenTopic(topic){ return [topic.id, topic.title, topic.category, topic.summary, topic.frequency, ...(topic.body||[]), ...(topic.recognitionTips||[]), ...(topic.principalParts||[]), ...(topic.paradigmTabs||[]).flatMap(tab=>[tab.label,...(tab.charts||[]).flatMap(c=>[c.label,c.note,...(c.columns||[]),...(c.rows||[]).flat().map(cellText)])]), ...(topic.charts||[]).flatMap(c=>[c.heading,c.label,c.note,c.color,...(c.columns||[]),...(c.rows||[]).flat().map(cellText)]), ...(topic.examples||[]).flatMap(e=>[e.word,e.reference,e.translation,e.note,e.text]), ...(topic.related||[]).map(topicLabel), ...(topic.featureLinks||[]).flatMap(l=>[l.label,l.type,l.target]), topic.stemRelationships?.root, ...(topic.stemRelationships?.stems||[]), ...(topic.stemRelationships?.explanation||[])].join(' '); }
  function searchReferenceTopics(query='', language='all'){
    const q = normalizeSearchText(String(query).trim());
    return topics.filter(t => (language === 'all' || t.language === language) && (!q || normalizeSearchText(flattenTopic(t)).includes(q)));
  }
  function decodeParsing(input){ const key=String(input||'').trim().toUpperCase().replace(/\s+/g,' '); return decoderEntries[key] || null; }
  const api = { referenceTopics: topics, searchReferenceTopics, getReferenceTopic: id => topics.find(t => t.id === id), topicLabel, referenceColors: COLORS, decodeParsing, decoderEntries };
  if(typeof module !== 'undefined' && module.exports) module.exports = api;
  root.PuritanReferenceLibrary = api;
})(typeof window !== 'undefined' ? window : globalThis);
